### ISSUE TITLE
[Question] Diferrent behavior of mujoco version

### ISSUE THREAD

**Issue by im-Kitsch** [openai/gym#2776] opened 2022-04-24 14:10 UTC
Hi, 

I wonder if there is an expectation of identical behavior over different plattform and mujoco version. 

I tested on my Ubuntu PC and MacOS, but they showed different behavior.  Using the same seed to initialize the environment, the intial state s_0 is different in different mujoco version.

I runned simply. 
```
import gym
gym.make('Ant-v2')
env.seed(0)
print(env.reset())
```

On my Ubuntu PC,
it shows:
```
array([ 1.25465391e+00,  1.32690946e-03, -2.09982656e-03, -3.97515743e-03,
        1.73076348e-03, -1.07423260e-03,  1.69846067e-03, -4.40161031e-03,
        2.69872445e-04, -4.59709307e-03,  4.77944075e-03])
```
On MacOS, it shows, 
```
array([ 1.24769787e+00, -4.59026476e-03, -4.83472364e-03,  3.13270239e-03,
        4.12755577e-03,  1.06635776e-03,  2.29496561e-03,  4.36249915e-04,
        4.35072424e-03,  3.15853554e-03, -4.97261500e-03])
```

My Ubuntu PC's configuration are :
mujoco_py: 2.0.2.13
Mujoco: Mujoco2.0.0 ([Mujoco200_linux](https://roboti.us/download.html#:~:text=mujoco200%20win64-,mujoco200%20linux,-mujoco200%20macos))
gym: 0.21.0
Python: 3.7.11

My MacBook's configuration are:
mujoco_py: 2.1.2.14
Mujoco: 2.1.1
gym: 0.23.1
CPU: Apple Silicon m1pro
Python: 3.9.12

I am not sure if the difference is considered as normal case or is a bug. Since theorically the environment should have the same performance in different platteforms and mujoco/mujoco_py versions, if the program uses same seed.

Looking forward to your reply.
Best.

**Comment by vwxyzjn** [comment] 2022-04-24 17:05
Can you get the same results with seeding in the Mac OS and Ubuntu, respectively?

in my past experience if I stayed with an operating system I can always reproduce same results with seeding, however all bets are off when using the same seed for different hardware / os.

**Comment by im-Kitsch** [comment] 2022-04-26 10:38
> Can you get the same results with seeding in the Mac OS and Ubuntu, respectively?
> 
> in my past experience if I stayed with an operating system I can always reproduce same results with seeding, however all bets are off when using the same seed for different hardware / os.

Hi, 

thanks for the reply, yes, I can get same result in same plattforms. But it would be more appreatiated, when man can get the same result in differrent plattforms. Since in most library, numpy, torch,..... are identical over different plattforms.  

But if there is differences due to different plattforms/mujoco_versions/other reasons, it will add pretty much difficulty for reproduceability of papers. 

Or even otherwise, it will also be very appreciated if we can know the how different over plattforms/mujoco versions, then it is more easier to analyze or debug by development. 

I think it would be definitely the problem of mujoco, but I am not sure if it relates to Mujoco itself or Mujoco_py or gym. 

thanks in advance.

**Comment by duburcqa** [comment] 2022-04-26 18:33
Different platforms are known to return different results when it comes to linear algebra using different hardware because the available instruction sets are different. As a result, the rounding errors are different and ultimately it diverges because of compounding of errors. Simulators are extremely sensitive to this phenomenon. The OS is likely not the problem but the rather the hardware. Note that it is basically the same than running on a different hardware when using mujoco on Apple M1 since it is not compiled to run natively and requires an emulator/compatibility layer to translate instructions, which is not the same as running native software. For ML libraries such as Pytorch, it does both of the CPU and GPU. Just changing the GPU would give different results.

Sadly, using fix-point integer math instead of classic floating point algebra is the only solution. [tiny-differentiable-simulator](https://github.com/erwincoumans/tiny-differentiable-simulator) is doing exactly that but only few simulators supports it.

**Comment by im-Kitsch** [comment] 2022-04-26 19:18
> Different platforms are known to return different results when it comes to linear algebra using different hardware because the available instruction sets are different. As a result, the rounding errors are different and ultimately it diverges because of compounding of errors. Simulators are extremely sensitive to this phenomenon. The OS is likely not the problem but the rather the hardware. Note that it is basically the same than running on a different hardware when using mujoco on Apple M1 since it is not compiled to run natively and requires an emulator/compatibility layer to translate instructions, which is not the same as running native software. For ML libraries such as Pytorch, it does both of the CPU and GPU. Just changing the GPU would give different results.
> 
> Sadly, using fix-point integer math instead of classic floating point algebra is the only solution. [tiny-differentiable-simulator](https://github.com/erwincoumans/tiny-differentiable-simulator) is doing exactly that but only few simulators supports it.

Hi, 

thanks a lot for the reply. It's quite help.

**Comment by vwxyzjn** [comment] 2022-04-26 19:20
@duburcqa thanks for the detailed explanation. @jkterry1 I think we can close this issue now.

**Closed** 2022-04-26 19:35 UTC
