### ISSUE TITLE
video_recorder trying to load StringIO with Python 3.5

### ISSUE THREAD

**Issue by muratozkan** [openai/gym#40] opened 2016-05-01 13:44 UTC
I am using Python 3.5.1 with `virtualenvwrapper` and a minimal gym installation via: 

`pip install gym`

You can reproduce this issue with the basic CartPole example in introduction: 

```python
import gym
env = gym.make('CartPole-v0')
env.reset()
for _ in range(1000):
    env.render()
    env.step(env.action_space.sample()) # take a random action
```

Running this script results in the following error

```
  File "cartpole.py", line 1, in <module>
    import gym
  File "/Users/ozkanm/.virtualenvs/gym/lib/python3.5/site-packages/gym/__init__.py", line 4, in <module>
    from gym.core import Env, Space
  File "/Users/ozkanm/.virtualenvs/gym/lib/python3.5/site-packages/gym/core.py", line 4, in <module>
    from gym import error, monitoring
  File "/Users/ozkanm/.virtualenvs/gym/lib/python3.5/site-packages/gym/monitoring/__init__.py", line 1, in <module>
    from gym.monitoring.monitor import Monitor, load_results, monitors as _monitors
  File "/Users/ozkanm/.virtualenvs/gym/lib/python3.5/site-packages/gym/monitoring/monitor.py", line 12, in <module>
    from gym.monitoring import stats_recorder, video_recorder
  File "/Users/ozkanm/.virtualenvs/gym/lib/python3.5/site-packages/gym/monitoring/video_recorder.py", line 9, in <module>
    import StringIO
ImportError: No module named 'StringIO'
```

**Comment by tlbtlbtlb** [comment] 2016-05-01 13:47
Dupe of issue #1. The Python 3 compatibility isn't released to PyPI yet; you have to install from source.

**Comment by gdb** [comment] 2016-05-01 13:48
(That being said, I'll cut a new release.)

**Closed by tlbtlbtlb** 2016-05-01 13:47 UTC
