### ISSUE TITLE
[Question] Failed to load XML file

### ISSUE THREAD

**Issue by t46** [openai/gym#2676] opened 2022-03-09 06:36 UTC
### Question
Hi, thanks for contribution.

When trying to make an environment, it gives me a following error. Any suggestions?

```{python}
import gym
env = gym.make('HalfCheetah-v3')
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/gym/envs/registration.py", line 676, in make
    return registry.make(id, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/gym/envs/registration.py", line 520, in make
    return spec.make(**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/gym/envs/registration.py", line 140, in make
    env = cls(**_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/gym/envs/mujoco/half_cheetah_v3.py", line 152, in __init__
    mujoco_env.MujocoEnv.__init__(self, xml_file, 5)
  File "/usr/local/lib/python3.8/dist-packages/gym/envs/mujoco/mujoco_env.py", line 54, in __init__
    self.model = mujoco_py.load_model_from_path(fullpath)
  File "cymj.pyx", line 175, in mujoco_py.cymj.load_model_from_path
Exception: Failed to load XML file: /usr/local/lib/python3.8/dist-packages/gym/envs/mujoco/assets/half_cheetah.xml. mj_loadXML error: b"Error: alternative specification error 'yaxis too small' in site 0\nObject name = track, id = 0, line = 55, column = 7"
```

half_cheetah.xml
```
<!-- Cheetah Model

    The state space is populated with joints in the order that they are
    defined in this file. The actuators also operate on joints.

    State-Space (name/joint/parameter):
        - rootx     slider      position (m)
        - rootz     slider      position (m)
        - rooty     hinge       angle (rad)
        - bthigh    hinge       angle (rad)
        - bshin     hinge       angle (rad)
        - bfoot     hinge       angle (rad)
        - fthigh    hinge       angle (rad)
        - fshin     hinge       angle (rad)
        - ffoot     hinge       angle (rad)
        - rootx     slider      velocity (m/s)
        - rootz     slider      velocity (m/s)
        - rooty     hinge       angular velocity (rad/s)
        - bthigh    hinge       angular velocity (rad/s)
        - bshin     hinge       angular velocity (rad/s)
        - bfoot     hinge       angular velocity (rad/s)
        - fthigh    hinge       angular velocity (rad/s)
        - fshin     hinge       angular velocity (rad/s)
        - ffoot     hinge       angular velocity (rad/s)

    Actuators (name/actuator/parameter):
        - bthigh    hinge       torque (N m)
        - bshin     hinge       torque (N m)
        - bfoot     hinge       torque (N m)
        - fthigh    hinge       torque (N m)
        - fshin     hinge       torque (N m)
        - ffoot     hinge       torque (N m)

-->
<mujoco model="cheetah">
  <compiler angle="radian" coordinate="local" inertiafromgeom="true" settotalmass="14"/>
  <default>
    <joint armature=".1" damping=".01" limited="true" solimplimit="0 .8 .03" solreflimit=".02 1" stiffness="8"/>
    <geom conaffinity="0" condim="3" contype="1" friction=".4 .1 .1" rgba="0.8 0.6 .4 1" solimp="0.0 0.8 0.01" solref="0.02 1"/>
    <motor ctrllimited="true" ctrlrange="-1 1"/>
  </default>
  <size nstack="300000" nuser_geom="1"/>
  <option gravity="0 0 -9.81" timestep="0.01"/>
  <asset>
    <texture builtin="gradient" height="100" rgb1="1 1 1" rgb2="0 0 0" type="skybox" width="100"/>
    <texture builtin="flat" height="1278" mark="cross" markrgb="1 1 1" name="texgeom" random="0.01" rgb1="0.8 0.6 0.4" rgb2="0.8 0.6 0.4" type="cube" width="127"/>
    <texture builtin="checker" height="100" name="texplane" rgb1="0 0 0" rgb2="0.8 0.8 0.8" type="2d" width="100"/>
    <material name="MatPlane" reflectance="0.5" shininess="1" specular="1" texrepeat="60 60" texture="texplane"/>
    <material name="geom" texture="texgeom" texuniform="true"/>
  </asset>
  <worldbody>
    <light cutoff="100" diffuse="1 1 1" dir="-0 0 -1.3" directional="true" exponent="1" pos="0 0 1.3" specular=".1 .1 .1"/>
    <geom conaffinity="1" condim="3" material="MatPlane" name="floor" pos="0 0 0" rgba="0.8 0.9 0.8 1" size="40 40 40" type="plane"/>
    <body name="torso" pos="0 0 .7">
      <camera name="track" mode="trackcom" pos="0 -3 0.3" xyaxes="1 0 0 0 0 1"/>
      <joint armature="0" axis="1 0 0" damping="0" limited="false" name="rootx" pos="0 0 0" stiffness="0" type="slide"/>
      <joint armature="0" axis="0 0 1" damping="0" limited="false" name="rootz" pos="0 0 0" stiffness="0" type="slide"/>
      <joint armature="0" axis="0 1 0" damping="0" limited="false" name="rooty" pos="0 0 0" stiffness="0" type="hinge"/>
      <geom fromto="-.5 0 0 .5 0 0" name="torso" size="0.046" type="capsule"/>
      <geom axisangle="0 1 0 .87" name="head" pos=".6 0 .1" size="0.046 .15" type="capsule"/>
      <!-- <site name='tip'  pos='.15 0 .11'/>-->
      <body name="bthigh" pos="-.5 0 0">
        <joint axis="0 1 0" damping="6" name="bthigh" pos="0 0 0" range="-.52 1.05" stiffness="240" type="hinge"/>
        <geom axisangle="0 1 0 -3.8" name="bthigh" pos=".1 0 -.13" size="0.046 .145" type="capsule"/>
        <body name="bshin" pos=".16 0 -.25">
          <joint axis="0 1 0" damping="4.5" name="bshin" pos="0 0 0" range="-.785 .785" stiffness="180" type="hinge"/>
          <geom axisangle="0 1 0 -2.03" name="bshin" pos="-.14 0 -.07" rgba="0.9 0.6 0.6 1" size="0.046 .15" type="capsule"/>
          <body name="bfoot" pos="-.28 0 -.14">
            <joint axis="0 1 0" damping="3" name="bfoot" pos="0 0 0" range="-.4 .785" stiffness="120" type="hinge"/>
            <geom axisangle="0 1 0 -.27" name="bfoot" pos=".03 0 -.097" rgba="0.9 0.6 0.6 1" size="0.046 .094" type="capsule"/>
          </body>
        </body>
      </body>
      <body name="fthigh" pos=".5 0 0">
        <joint axis="0 1 0" damping="4.5" name="fthigh" pos="0 0 0" range="-1 .7" stiffness="180" type="hinge"/>
        <geom axisangle="0 1 0 .52" name="fthigh" pos="-.07 0 -.12" size="0.046 .133" type="capsule"/>
        <body name="fshin" pos="-.14 0 -.24">
          <joint axis="0 1 0" damping="3" name="fshin" pos="0 0 0" range="-1.2 .87" stiffness="120" type="hinge"/>
          <geom axisangle="0 1 0 -.6" name="fshin" pos=".065 0 -.09" rgba="0.9 0.6 0.6 1" size="0.046 .106" type="capsule"/>
          <body name="ffoot" pos=".13 0 -.18">
            <joint axis="0 1 0" damping="1.5" name="ffoot" pos="0 0 0" range="-.5 .5" stiffness="60" type="hinge"/>
            <geom axisangle="0 1 0 -.6" name="ffoot" pos=".045 0 -.07" rgba="0.9 0.6 0.6 1" size="0.046 .07" type="capsule"/>
          </body>
        </body>
      </body>
    </body>
  </worldbody>
  <actuator>
    <motor gear="120" joint="bthigh" name="bthigh"/>
    <motor gear="90" joint="bshin" name="bshin"/>
    <motor gear="60" joint="bfoot" name="bfoot"/>
    <motor gear="120" joint="fthigh" name="fthigh"/>
    <motor gear="60" joint="fshin" name="fshin"/>
    <motor gear="30" joint="ffoot" name="ffoot"/>
  </actuator>
</mujoco>
```

**Comment by vwxyzjn** [comment] 2022-03-11 03:17
Hey I can't reproduce this:

![image](https://user-images.githubusercontent.com/5555347/157795481-e921d10c-ef76-4d5c-ae5a-5571b930125c.png)

**Comment by t46** [comment] 2022-03-11 08:33
Thank you for the quick response. I'm sorry I was not clear. I updated the system info.

**Code example**
Running command below reproduces the result.
```
docker build --platform=linux/amd64 . -t gym
docker run -it -v ~/.mujoco/:/root/.mujoco --name gym --platform linux/amd64 gym
python
>>> import gym
>>> env = gym.make('HalfCheetah-v3')
```
Dockerfile is below.
```
FROM python:3.8-slim-buster
RUN apt update && apt install -y \
         vim \
         git \
         build-essential \
         patchelf \
         libosmesa6-dev \
         libgl1-mesa-glx \
         libglfw3
RUN ln -s /usr/lib/x86_64-linux-gnu/libGL.so.1 /usr/lib/x86_64-linux-gnu/libGL.so
RUN pip3 install -U \
         'mujoco-py<2.2,>=2.1' \
         gym
ENV LD_LIBRARY_PATH=/root/.mujoco/mujoco210/bin/
CMD ["bash"]
``` 

**System Info**
   * Macbook Pro / Apple M1 Pro / macOS Monterey 12.0.1
   * docker version
     ```
      Client:
       Cloud integration: v1.0.22
       Version:           20.10.12
       API version:       1.41
       Go version:        go1.16.12
       Git commit:        e91ed57
       Built:             Mon Dec 13 11:46:56 2021
       OS/Arch:           darwin/arm64
       Context:           default
       Experimental:      true

      Server: Docker Desktop 4.5.0 (74594)
       Engine:
        Version:          20.10.12
        API version:      1.41 (minimum version 1.12)
        Go version:       go1.16.12
        Git commit:       459d0df
        Built:            Mon Dec 13 11:43:07 2021
        OS/Arch:          linux/arm64
        Experimental:     false
       containerd:
        Version:          1.4.12
        GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
       runc:
        Version:          1.0.2
        GitCommit:        v1.0.2-0-g52b36a2
       docker-init:
        Version:          0.19.0
        GitCommit:        de40ad0     
     ```
 * Python 3.8.12

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/openai/gym/issues) in the repo (**required**)

**Comment by TianhongDai** [comment] 2022-05-20 22:48
I also have the same error.

**Comment by jkterry1** [comment] 2022-05-23 18:52
PR #2762 is about to be merged, introducing V4 MuJoCo environments using new bindings and a dramatically newer version of the engine. If this issue still persists with the V4 ones, please create a new issue for it.

**Closed by jkterry1** 2022-05-23 18:52 UTC
Labels: mujoco
