### ISSUE TITLE
Error with the installation 

### ISSUE THREAD

**Issue by deepSalva** [openai/gym#947] opened 2018-03-13 18:29 UTC
Hi there, I got this issue when I try: 

> pip install -e .[all]

I followed the install instructions, first with: 

> git clone https://github.com/openai/gym
> cd gym
> pip install -e .

then I upgrade pip with: 

> pip install --upgrade setuptools

Now I got this error message: 

> Command "C:\Users\salva\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\salva\\AppData\\Loc
> al\\Temp\\pip-build-_1k0tc5c\\atari-py\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\
> n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\salva\AppData\Local\Temp\pip-fpld6y
> y9-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\salva\A
> ppData\Local\Temp\pip-build-_1k0tc5c\atari-py\

**Comment by danisaza** [comment] 2018-03-16 00:16
I'm having the same issue when running `docker build .` from within the `gym` directory.

I've added `pip install --upgrade setuptools` just before `pip install -e .[all]` in the Dockerfile, which didn't fix the issue (modified snippet from my Dockerfile is below).

So now my Dockerfile looks like this (note that this is just a part of it):
```
WORKDIR /usr/local/gym
RUN mkdir -p gym && touch gym/__init__.py
COPY ./gym/version.py ./gym
COPY ./requirements.txt .
COPY ./setup.py .
RUN pip install --upgrade setuptools # I added this
RUN sudo pip install -e .[all] # note that I added `sudo` here
```

It seems like the issue is occurring while downloading the `mujoco` package, whose `setup.py` file is attempting to import `importlib.util`, where `util` does not exist (`ImportError: No module named util`).

I've created [this github gist](https://gist.github.com/danisaza/7828534d4b996f5e31bf988ce2f21c25) with the full output of running `docker build .`.

I'm currently looking into an `InsecurePlatformWarning` from `urllib3` and will post updates here.

If someone has helpful context to share, please reach out! 😃

**Comment by pzhokhov** [comment] 2018-09-14 23:27
probably fixed now, but please use test.dockerfile instead of Dockerfile - that's the one our CI is based on, so it must be working ^_^

**Closed by pzhokhov** 2018-09-14 23:27 UTC
