### ISSUE TITLE
[Bug Report] Non-Integer smaller_cell_scale causes FrozenLake to crash on Render

### ISSUE THREAD

**Issue by jrieffel** [openai/gym#2723] opened 2022-04-01 02:26 UTC
If you are submitting a bug report, please fill in the following details and use the tag [bug].

**Describe the bug**

**Code example**

On a Mac running python3:

```
import gym # loading the Gym library
env = gym.make("FrozenLake-v1")
env.reset()                    
while(True):
    env.render()
```

crashes with error:

 start_img = pygame.transform.scale(self.start_img, (small_cell_w, small_cell_h))
TypeError: integer argument expected, got float

**System Info**
Describe the characteristic of your environment:

MacOS running Python 3.8

**Additional context**

I could eliminate the problem by manually changing smaller_cell_scale to 1

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/openai/gym/issues) in the repo (**required**)

**Comment by pseudo-rnd-thoughts** [comment] 2022-04-01 15:51
I have run this with the current main branch on Python 3.9 and pygame 2.1.2 and I can't replicate this issue

Are you running on the latest gym and pygame version?

**Comment by younik** [comment] 2022-04-15 11:44
I am not able to reproduce the error, I think it is due to an older version of pygame.
Nevertheless, casting small_cell sizes to int doesn't hurt; #2754 should fix this.

**Comment by pseudo-rnd-thoughts** [comment] 2022-04-15 13:41
@jrieffel Does this address your issue? If so, could you close the issue

**Closed** 2022-04-15 15:03 UTC
