### ISSUE TITLE
sample() in gym.spaces.Box does not work for (high=255, dtype=np.uint8)

### ISSUE THREAD

**Issue by ahtsan** [openai/gym#1279] opened 2019-01-08 05:45 UTC
In your implementation
```python
def sample(self):
            return gym.spaces.np_random.uniform(low=self.low, high=self.high + (0 if self.dtype.kind == 'f' else 1), size=self.low.shape).astype(self.dtype)
```
if self.high = 255, self.high + 1 will not work since np.uint8 has a max value of 255, it will cause overflow.

**Comment by afrozenator** [comment] 2019-01-11 05:00
Duplicate of #1256

**Comment by christopherhesse** [comment] 2019-02-09 00:42
Thanks for fixing this @pzhokhov, this has been bugging me for awhile.

**Closed by christopherhesse** 2019-02-09 00:42 UTC
