### ISSUE TITLE
Failed to render: Symbol not found

### ISSUE THREAD

**Issue by hughplay** [openai/gym#1452] opened 2019-04-22 03:25 UTC
Hi,

I am struggling to make `env.render()` work on my Mac.

When I running the code below:

``` py
import gym
env = gym.make('CartPole-v0')
env.reset()
for _ in range(1000):
    env.render()
    env.step(env.action_space.sample()) # take a random action
env.close()
```

Error raised:

```
Traceback (most recent call last):
  File "dqn.py", line 5, in <module>
    env.render()
  File "/Users/hugh/Documents/code/project/rl/gym/gym/core.py", line 249, in render
    return self.env.render(mode, **kwargs)
  File "/Users/hugh/Documents/code/project/rl/gym/gym/envs/classic_control/cartpole.py", line 150, in render
    from gym.envs.classic_control import rendering
  File "/Users/hugh/Documents/code/project/rl/gym/gym/envs/classic_control/rendering.py", line 27, in <module>
    from pyglet.gl import *
  File "/Users/hugh/anaconda3/lib/python3.6/site-packages/pyglet/gl/__init__.py", line 100, in <module>
    from pyglet.gl.lib import GLException
  File "/Users/hugh/anaconda3/lib/python3.6/site-packages/pyglet/gl/lib.py", line 141, in <module>
    from pyglet.gl.lib_agl import link_GL, link_GLU, link_AGL
  File "/Users/hugh/anaconda3/lib/python3.6/site-packages/pyglet/gl/lib_agl.py", line 51, in <module>
    framework='/System/Library/Frameworks/AGL.framework')
  File "/Users/hugh/anaconda3/lib/python3.6/site-packages/pyglet/lib.py", line 118, in load_library
    return self.load_framework(kwargs['framework'])
  File "/Users/hugh/anaconda3/lib/python3.6/site-packages/pyglet/lib.py", line 279, in load_framework
    lib = ctypes.cdll.LoadLibrary(realpath)
  File "/Users/hugh/anaconda3/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/Users/hugh/anaconda3/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/System/Library/Frameworks/AGL.framework/AGL, 6): Symbol not found: _CGLChoosePixelFormat
  Referenced from: /System/Library/Frameworks/AGL.framework/Versions/A/AGL
  Expected in: flat namespace
 in /System/Library/Frameworks/AGL.framework/Versions/A/AGL
```

The environment of mine is shown below:

- System: macOS Mojave 10.14.4
- xcode-select version 2354
- conda: 4.6.13
- Python 3.6.8 :: Anaconda, Inc.

And of course I installed the dependencies by running the following command:

``` sh
brew install cmake boost boost-python sdl2 swig wget
```

So could you help me with this problem?
I find nothing similar with googling and updating `xcode-select` seems not help at all.

**Comment by hughplay** [comment] 2019-04-22 03:45
I found I can run `Breakout-v0` successfully in jupyter lab:

``` py
import gym
from IPython import display
import matplotlib.pyplot as plt
%matplotlib inline

env = gym.make('Breakout-v0')
env.reset()
for _ in range(1000):
    plt.imshow(env.render(mode='rgb_array'))
    display.clear_output(wait=True)
    display.display(plt.gcf())
    env.step(env.action_space.sample())
```

![image](https://user-images.githubusercontent.com/30553791/56481828-8acc8300-64f3-11e9-9b89-91dbbe7fd440.png)

But it still failed with `CartPole-v0` and `CartPole-v1` and all [classic control](https://gym.openai.com/envs/#classic_control).

Error when running `CartPole-v0`:

```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-25-bd78134a2c9e> in <module>
      7 env.reset()
      8 for _ in range(1000):
----> 9     plt.imshow(env.render(mode='rgb_array'))
     10     display.clear_output(wait=True)
     11     display.display(plt.gcf())

~/Documents/code/project/rl/gym/gym/core.py in render(self, mode, **kwargs)
    247 
    248     def render(self, mode='human', **kwargs):
--> 249         return self.env.render(mode, **kwargs)
    250 
    251     def close(self):

~/Documents/code/project/rl/gym/gym/envs/classic_control/cartpole.py in render(self, mode)
    148 
    149         if self.viewer is None:
--> 150             from gym.envs.classic_control import rendering
    151             self.viewer = rendering.Viewer(screen_width, screen_height)
    152             l,r,t,b = -cartwidth/2, cartwidth/2, cartheight/2, -cartheight/2

~/Documents/code/project/rl/gym/gym/envs/classic_control/rendering.py in <module>
     25 
     26 try:
---> 27     from pyglet.gl import *
     28 except ImportError as e:
     29     raise ImportError('''

~/anaconda3/lib/python3.6/site-packages/pyglet/gl/__init__.py in <module>
    222 elif compat_platform == 'darwin':
    223     if _pyglet.options['darwin_cocoa']:
--> 224         from .cocoa import CocoaConfig as Config
    225     else:
    226         from .carbon import CarbonConfig as Config

~/anaconda3/lib/python3.6/site-packages/pyglet/gl/cocoa.py in <module>
     15 from pyglet.gl import agl
     16 
---> 17 from pyglet.canvas.cocoa import CocoaCanvas
     18 
     19 from pyglet.libs.darwin.cocoapy import *

~/anaconda3/lib/python3.6/site-packages/pyglet/canvas/__init__.py in <module>
     89         from pyglet import options as pyglet_options
     90         if pyglet_options['darwin_cocoa']:
---> 91             from pyglet.canvas.cocoa import CocoaDisplay as Display
     92             from pyglet.canvas.cocoa import CocoaScreen as Screen
     93             from pyglet.canvas.cocoa import CocoaCanvas as Canvas

~/anaconda3/lib/python3.6/site-packages/pyglet/canvas/cocoa.py in <module>
     14 from .base import Display, Screen, ScreenMode, Canvas
     15 
---> 16 from pyglet.libs.darwin.cocoapy import *
     17 
     18 

~/anaconda3/lib/python3.6/site-packages/pyglet/libs/darwin/__init__.py in <module>
      5 if pyglet.options['darwin_cocoa']:
      6 
----> 7     from .cocoapy import *
      8 
      9 # Carbon implementation:

~/anaconda3/lib/python3.6/site-packages/pyglet/libs/darwin/cocoapy/__init__.py in <module>
     35 
     36 from .cocoatypes import *
---> 37 from .cocoalibs import *

~/anaconda3/lib/python3.6/site-packages/pyglet/libs/darwin/cocoapy/cocoalibs.py in <module>
    334 # QUARTZ / COREGRAPHICS
    335 
--> 336 quartz = cdll.LoadLibrary(util.find_library('quartz'))
    337 
    338 CGDirectDisplayID = c_uint32     # CGDirectDisplay.h

~/anaconda3/lib/python3.6/ctypes/__init__.py in LoadLibrary(self, name)
    424 
    425     def LoadLibrary(self, name):
--> 426         return self._dlltype(name)
    427 
    428 cdll = LibraryLoader(CDLL)

~/anaconda3/lib/python3.6/ctypes/__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error)
    346 
    347         if handle is None:
--> 348             self._handle = _dlopen(self._name, mode)
    349         else:
    350             self._handle = handle

OSError: dlopen(/System/Library/Frameworks/quartz.framework/quartz, 6): Symbol not found: _NSAccessibilityDecrementAction
  Referenced from: /System/Library/Frameworks/QTKit.framework/Versions/A/QTKit
  Expected in: flat namespace
 in /System/Library/Frameworks/QTKit.framework/Versions/A/QTKit
```

**Comment by christopherhesse** [comment] 2019-04-25 21:58
It looks like your mac os libraries are all broken, can you try on a different mac?

**Comment by hughplay** [comment] 2019-04-26 04:22
I think you are right.
I make gym run on my Mac with docker and `render` in jupyter notebook.

No idea about how to fix os libraries...

**Comment by christopherhesse** [comment] 2019-04-26 21:40
Could you try reinstalling the operating system?  I don't think I've seen mac os frameworks unable to find symbols before.

**Comment by hughplay** [comment] 2019-04-27 03:05
That will be a huge engineering.
I will try when I get some time.  :sweat_smile:

**Comment by christopherhesse** [comment] 2019-05-03 21:38
Okay, I'm going to close this issue for now since I doubt it could be reproduced anyway.  Please file a new issue if this happens on multiple machines.

**Closed by christopherhesse** 2019-05-03 21:38 UTC

**Comment by hughplay** [comment] 2019-05-31 05:31
I finally find this problem is caused by `export DYLD_FORCE_FLAT_NAMESPACE=1` in my `.zshrc`.
It was used for fixing python crash with vim and YCM plugin. Now I use neovim so everything is fine now., except I reinstalled my system before I found this...

**Comment by VineetTambe** [comment] 2020-03-22 14:05
Okay, but how do you resolve this issue?
