### ISSUE TITLE
Yet another "Building wheel for mujoco-py (setup.py) ... error"

### ISSUE THREAD

**Issue by joehays** [openai/gym#1883] opened 2020-04-15 15:59 UTC
All,

There are a number of **_"Building wheel for mujoco-py (setup.py) ... error"_** postings but none have helped me resolve my problem. I believe that I have followed the directions from,

https://spinningup.openai.com/en/latest/user/installation.html

and,

https://github.com/openai/mujoco-py

accurately...  Here is the full error,

```
(spinningup) joehays@scylla:~$ pip install 'gym[mujoco,robotics]'
Requirement already satisfied: gym[mujoco,robotics] in ./apps/miniconda/envs/spinningup/lib/python3.6/site-packages (0.15.7)
Requirement already satisfied: scipy in ./apps/miniconda/envs/spinningup/lib/python3.6/site-packages (from gym[mujoco,robotics]) (1.4.1)
Requirement already satisfied: six in ./apps/miniconda/envs/spinningup/lib/python3.6/site-packages (from gym[mujoco,robotics]) (1.14.0)
Requirement already satisfied: pyglet<=1.5.0,>=1.4.0 in ./apps/miniconda/envs/spinningup/lib/python3.6/site-packages (from gym[mujoco,robotics]) (1.5.0)
Requirement already satisfied: numpy>=1.10.4 in ./apps/miniconda/envs/spinningup/lib/python3.6/site-packages (from gym[mujoco,robotics]) (1.18.2)
Requirement already satisfied: cloudpickle~=1.2.0 in ./apps/miniconda/envs/spinningup/lib/python3.6/site-packages (from gym[mujoco,robotics]) (1.2.1)
Requirement already satisfied: imageio; extra == "mujoco" in ./apps/miniconda/envs/spinningup/lib/python3.6/site-packages (from gym[mujoco,robotics]) (2.8.0)
Collecting mujoco-py<2.0,>=1.50; extra == "mujoco"
  Using cached mujoco-py-1.50.1.68.tar.gz (120 kB)
Requirement already satisfied: future in ./apps/miniconda/envs/spinningup/lib/python3.6/site-packages (from pyglet<=1.5.0,>=1.4.0->gym[mujoco,robotics]) (0.18.2)
Requirement already satisfied: pillow in ./apps/miniconda/envs/spinningup/lib/python3.6/site-packages (from imageio; extra == "mujoco"->gym[mujoco,robotics]) (7.1.1)
Requirement already satisfied: glfw>=1.4.0 in ./apps/miniconda/envs/spinningup/lib/python3.6/site-packages (from mujoco-py<2.0,>=1.50; extra == "mujoco"->gym[mujoco,robotics]) (1.11.0)
Requirement already satisfied: Cython>=0.27.2 in ./apps/miniconda/envs/spinningup/lib/python3.6/site-packages (from mujoco-py<2.0,>=1.50; extra == "mujoco"->gym[mujoco,robotics]) (0.29.16)
Requirement already satisfied: cffi>=1.10 in ./apps/miniconda/envs/spinningup/lib/python3.6/site-packages (from mujoco-py<2.0,>=1.50; extra == "mujoco"->gym[mujoco,robotics]) (1.14.0)
Requirement already satisfied: lockfile>=0.12.2 in ./apps/miniconda/envs/spinningup/lib/python3.6/site-packages (from mujoco-py<2.0,>=1.50; extra == "mujoco"->gym[mujoco,robotics]) (0.12.2)
Requirement already satisfied: pycparser in ./apps/miniconda/envs/spinningup/lib/python3.6/site-packages (from cffi>=1.10->mujoco-py<2.0,>=1.50; extra == "mujoco"->gym[mujoco,robotics]) (2.20)
Building wheels for collected packages: mujoco-py
  Building wheel for mujoco-py (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/joehays/apps/miniconda/envs/spinningup/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-c1eqt3bt/mujoco-py/setup.py'"'"'; __file__='"'"'/tmp/pip-install-c1eqt3bt/mujoco-py/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-zy3zis9l
       cwd: /tmp/pip-install-c1eqt3bt/mujoco-py/
  Complete output (54 lines):
  running bdist_wheel
  running build
  
  You appear to be missing MuJoCo.  We expected to find the file here: /home/joehays/.mujoco/mjpro150
  
  This package only provides python bindings, the library must be installed separately.
  
  Please follow the instructions on the README to install MuJoCo
  
      https://github.com/openai/mujoco-py#install-mujoco
  
  Which can be downloaded from the website
  
      https://www.roboti.us/index.html
  
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-c1eqt3bt/mujoco-py/setup.py", line 44, in <module>
      tests_require=read_requirements_file('requirements.dev.txt'),
    File "/home/joehays/apps/miniconda/envs/spinningup/lib/python3.6/site-packages/setuptools/__init__.py", line 144, in setup
      return distutils.core.setup(**attrs)
    File "/home/joehays/apps/miniconda/envs/spinningup/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/joehays/apps/miniconda/envs/spinningup/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/home/joehays/apps/miniconda/envs/spinningup/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/joehays/apps/miniconda/envs/spinningup/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "/home/joehays/apps/miniconda/envs/spinningup/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/joehays/apps/miniconda/envs/spinningup/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-c1eqt3bt/mujoco-py/setup.py", line 28, in run
      import mujoco_py  # noqa: force build
    File "/tmp/pip-install-c1eqt3bt/mujoco-py/mujoco_py/__init__.py", line 3, in <module>
      from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
    File "/tmp/pip-install-c1eqt3bt/mujoco-py/mujoco_py/builder.py", line 502, in <module>
      mjpro_path, key_path = discover_mujoco()
    File "/tmp/pip-install-c1eqt3bt/mujoco-py/mujoco_py/utils.py", line 93, in discover_mujoco
      raise Exception(message)
  Exception:
  You appear to be missing MuJoCo.  We expected to find the file here: /home/joehays/.mujoco/mjpro150
  
  This package only provides python bindings, the library must be installed separately.
  
  Please follow the instructions on the README to install MuJoCo
  
      https://github.com/openai/mujoco-py#install-mujoco
  
  Which can be downloaded from the website
  
      https://www.roboti.us/index.html
  
  ----------------------------------------
  ERROR: Failed building wheel for mujoco-py
  Running setup.py clean for mujoco-py
Failed to build mujoco-py
Installing collected packages: mujoco-py
  Attempting uninstall: mujoco-py
    Found existing installation: mujoco-py 2.0.2.9
    Uninstalling mujoco-py-2.0.2.9:
      Successfully uninstalled mujoco-py-2.0.2.9
    Running setup.py install for mujoco-py ... error
    ERROR: Command errored out with exit status 1:
     command: /home/joehays/apps/miniconda/envs/spinningup/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-c1eqt3bt/mujoco-py/setup.py'"'"'; __file__='"'"'/tmp/pip-install-c1eqt3bt/mujoco-py/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-e4zxlpo1/install-record.txt --single-version-externally-managed --compile --install-headers /home/joehays/apps/miniconda/envs/spinningup/include/python3.6m/mujoco-py
         cwd: /tmp/pip-install-c1eqt3bt/mujoco-py/
    Complete output (56 lines):
    running install
    running build
    
    You appear to be missing MuJoCo.  We expected to find the file here: /home/joehays/.mujoco/mjpro150
    
    This package only provides python bindings, the library must be installed separately.
    
    Please follow the instructions on the README to install MuJoCo
    
        https://github.com/openai/mujoco-py#install-mujoco
    
    Which can be downloaded from the website
    
        https://www.roboti.us/index.html
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-c1eqt3bt/mujoco-py/setup.py", line 44, in <module>
        tests_require=read_requirements_file('requirements.dev.txt'),
      File "/home/joehays/apps/miniconda/envs/spinningup/lib/python3.6/site-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/home/joehays/apps/miniconda/envs/spinningup/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/joehays/apps/miniconda/envs/spinningup/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/home/joehays/apps/miniconda/envs/spinningup/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/joehays/apps/miniconda/envs/spinningup/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/home/joehays/apps/miniconda/envs/spinningup/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/home/joehays/apps/miniconda/envs/spinningup/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/joehays/apps/miniconda/envs/spinningup/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-c1eqt3bt/mujoco-py/setup.py", line 28, in run
        import mujoco_py  # noqa: force build
      File "/tmp/pip-install-c1eqt3bt/mujoco-py/mujoco_py/__init__.py", line 3, in <module>
        from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
      File "/tmp/pip-install-c1eqt3bt/mujoco-py/mujoco_py/builder.py", line 502, in <module>
        mjpro_path, key_path = discover_mujoco()
      File "/tmp/pip-install-c1eqt3bt/mujoco-py/mujoco_py/utils.py", line 93, in discover_mujoco
        raise Exception(message)
    Exception:
    You appear to be missing MuJoCo.  We expected to find the file here: /home/joehays/.mujoco/mjpro150
    
    This package only provides python bindings, the library must be installed separately.
    
    Please follow the instructions on the README to install MuJoCo
    
        https://github.com/openai/mujoco-py#install-mujoco
    
    Which can be downloaded from the website
    
        https://www.roboti.us/index.html
    
    ----------------------------------------
  Rolling back uninstall of mujoco-py
  Moving to /home/joehays/apps/miniconda/envs/spinningup/lib/python3.6/site-packages/mujoco_py-2.0.2.9.dist-info/
   from /home/joehays/apps/miniconda/envs/spinningup/lib/python3.6/site-packages/~ujoco_py-2.0.2.9.dist-info
  Moving to /home/joehays/apps/miniconda/envs/spinningup/lib/python3.6/site-packages/mujoco_py/__init__.py
   from /tmp/pip-uninstall-igxeph_0/__init__.py
  Moving to /home/joehays/apps/miniconda/envs/spinningup/lib/python3.6/site-packages/mujoco_py/__pycache__/
   from /home/joehays/apps/miniconda/envs/spinningup/lib/python3.6/site-packages/mujoco_py/~_pycache__
  Moving to /home/joehays/apps/miniconda/envs/spinningup/lib/python3.6/site-packages/mujoco_py/builder.py
   from /tmp/pip-uninstall-igxeph_0/builder.py
  Moving to /home/joehays/apps/miniconda/envs/spinningup/lib/python3.6/site-packages/mujoco_py/cymj.c
   from /tmp/pip-uninstall-igxeph_0/cymj.c
  Moving to /home/joehays/apps/miniconda/envs/spinningup/lib/python3.6/site-packages/mujoco_py/cymj.pyx
   from /tmp/pip-uninstall-igxeph_0/cymj.pyx
  Moving to /home/joehays/apps/miniconda/envs/spinningup/lib/python3.6/site-packages/mujoco_py/generated/__init__.py
   from /tmp/pip-uninstall-igxeph_0/generated/__init__.py
  Moving to /home/joehays/apps/miniconda/envs/spinningup/lib/python3.6/site-packages/mujoco_py/generated/__pycache__/
   from /home/joehays/apps/miniconda/envs/spinningup/lib/python3.6/site-packages/mujoco_py/generated/~_pycache__
  Moving to /home/joehays/apps/miniconda/envs/spinningup/lib/python3.6/site-packages/mujoco_py/generated/const.py
   from /tmp/pip-uninstall-igxeph_0/generated/const.py
  Moving to /home/joehays/apps/miniconda/envs/spinningup/lib/python3.6/site-packages/mujoco_py/generated/cymj_2.0.2.9_36_linuxgpuextensionbuilder_36.so
   from /tmp/pip-uninstall-igxeph_0/generated/cymj_2.0.2.9_36_linuxgpuextensionbuilder_36.so
  Moving to /home/joehays/apps/miniconda/envs/spinningup/lib/python3.6/site-packages/mujoco_py/generated/wrappers.pxi
   from /tmp/pip-uninstall-igxeph_0/generated/wrappers.pxi
  Moving to /home/joehays/apps/miniconda/envs/spinningup/lib/python3.6/site-packages/mujoco_py/gl/
   from /home/joehays/apps/miniconda/envs/spinningup/lib/python3.6/site-packages/mujoco_py/~l
  Moving to /home/joehays/apps/miniconda/envs/spinningup/lib/python3.6/site-packages/mujoco_py/mjbatchrenderer.pyx
   from /tmp/pip-uninstall-igxeph_0/mjbatchrenderer.pyx
  Moving to /home/joehays/apps/miniconda/envs/spinningup/lib/python3.6/site-packages/mujoco_py/mjpid.pyx
   from /tmp/pip-uninstall-igxeph_0/mjpid.pyx
  Moving to /home/joehays/apps/miniconda/envs/spinningup/lib/python3.6/site-packages/mujoco_py/mjrendercontext.pyx
   from /tmp/pip-uninstall-igxeph_0/mjrendercontext.pyx
  Moving to /home/joehays/apps/miniconda/envs/spinningup/lib/python3.6/site-packages/mujoco_py/mjrenderpool.py
   from /tmp/pip-uninstall-igxeph_0/mjrenderpool.py
  Moving to /home/joehays/apps/miniconda/envs/spinningup/lib/python3.6/site-packages/mujoco_py/mjsim.pyx
   from /tmp/pip-uninstall-igxeph_0/mjsim.pyx
  Moving to /home/joehays/apps/miniconda/envs/spinningup/lib/python3.6/site-packages/mujoco_py/mjsimstate.pyx
   from /tmp/pip-uninstall-igxeph_0/mjsimstate.pyx
  Moving to /home/joehays/apps/miniconda/envs/spinningup/lib/python3.6/site-packages/mujoco_py/mjviewer.py
   from /tmp/pip-uninstall-igxeph_0/mjviewer.py
  Moving to /home/joehays/apps/miniconda/envs/spinningup/lib/python3.6/site-packages/mujoco_py/modder.py
   from /tmp/pip-uninstall-igxeph_0/modder.py
  Moving to /home/joehays/apps/miniconda/envs/spinningup/lib/python3.6/site-packages/mujoco_py/opengl_context.pyx
   from /tmp/pip-uninstall-igxeph_0/opengl_context.pyx
  Moving to /home/joehays/apps/miniconda/envs/spinningup/lib/python3.6/site-packages/mujoco_py/pxd/
   from /home/joehays/apps/miniconda/envs/spinningup/lib/python3.6/site-packages/mujoco_py/~xd
  Moving to /home/joehays/apps/miniconda/envs/spinningup/lib/python3.6/site-packages/mujoco_py/tests/
   from /home/joehays/apps/miniconda/envs/spinningup/lib/python3.6/site-packages/mujoco_py/~ests
  Moving to /home/joehays/apps/miniconda/envs/spinningup/lib/python3.6/site-packages/mujoco_py/utils.py
   from /tmp/pip-uninstall-igxeph_0/utils.py
  Moving to /home/joehays/apps/miniconda/envs/spinningup/lib/python3.6/site-packages/mujoco_py/version.py
   from /tmp/pip-uninstall-igxeph_0/version.py
ERROR: Command errored out with exit status 1: /home/joehays/apps/miniconda/envs/spinningup/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-c1eqt3bt/mujoco-py/setup.py'"'"'; __file__='"'"'/tmp/pip-install-c1eqt3bt/mujoco-py/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-e4zxlpo1/install-record.txt --single-version-externally-managed --compile --install-headers /home/joehays/apps/miniconda/envs/spinningup/include/python3.6m/mujoco-py 
Check the logs for full command output.
```

**_You'll notice that it's looking for Mujoco 1.5... I did have an old version of Mujoco 1.5 on my machine but I replaced it with Mujoco 2.0. I also updated my mjkey.txt for the 2.0 version,_**

```
(spinningup) joehays@scylla:~$ tree ~/.mujoco/
/home/joehays/.mujoco/
├── mjkey.txt
└── mujoco200
    ├── bin
    │   ├── basic
    │   ├── compile
    │   ├── derivative
    │   ├── libglewegl.so
    │   ├── libglewosmesa.so
    │   ├── libglew.so
    │   ├── libglfw3.a
    │   ├── libglfw.so.3
    │   ├── libmujoco200nogl.so
    │   ├── libmujoco200.so
    │   ├── record
    │   ├── simulate
    │   ├── testspeed
    │   └── testxml
    ├── doc
    │   ├── README.txt
    │   └── REFERENCE.txt
    ├── include
    │   ├── glfw3.h
    │   ├── mjdata.h
    │   ├── mjmodel.h
    │   ├── mjrender.h
    │   ├── mjui.h
    │   ├── mjvisualize.h
    │   ├── mjxmacro.h
    │   ├── mujoco.h
    │   ├── uitools.c
    │   └── uitools.h
    ├── model
    │   ├── arm26.xml
    │   ├── carpet.png
    │   ├── cloth.xml
    │   ├── grid1pin.xml
    │   ├── grid1.xml
    │   ├── grid2pin.xml
    │   ├── grid2.xml
    │   ├── hammock.xml
    │   ├── humanoid100.xml
    │   ├── humanoid.xml
    │   ├── loop.xml
    │   ├── marble.png
    │   ├── particle.xml
    │   ├── rope.xml
    │   ├── scene.xml
    │   ├── softbox.xml
    │   ├── softcylinder.xml
    │   ├── softellipsoid.xml
    │   └── sponge.png
    └── sample
        ├── basic.cpp
        ├── compile.cpp
        ├── derivative.cpp
        ├── makefile
        ├── mjx.cpp
        ├── mjxmake.m
        ├── record.cpp
        ├── simulate.cpp
        ├── testspeed.cpp
        └── testxml.cpp

6 directories, 56 files
```

**_And, the basic Mujoco 2.0 test passes,_**

```
(spinningup) joehays@scylla:~$ python
Python 3.6.10 |Anaconda, Inc.| (default, Mar 25 2020, 23:51:54) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mujoco_py
>>> import os
>>> mj_path, _ = mujoco_py.utils.discover_mujoco()
>>> xml_path = os.path.join(mj_path, 'model', 'humanoid.xml')
>>> model = mujoco_py.load_model_from_path(xml_path)
>>> sim = mujoco_py.MjSim(model)
>>> 
>>> print(sim.data.qpos)
[0.  0.  1.4 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
 0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
>>> # [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
... 
>>> sim.step()
>>> print(sim.data.qpos)
[-1.12164337e-05  7.29847036e-22  1.39975300e+00  9.99999999e-01
  1.80085466e-21  4.45933954e-05 -2.70143345e-20  1.30126513e-19
 -4.63561234e-05 -1.88020744e-20 -2.24492958e-06  4.79357124e-05
 -6.38208396e-04 -1.61130312e-03 -1.37554006e-03  5.54173825e-05
 -2.24492958e-06  4.79357124e-05 -6.38208396e-04 -1.61130312e-03
 -1.37554006e-03 -5.54173825e-05 -5.73572648e-05  7.63833991e-05
 -2.12765194e-05  5.73572648e-05 -7.63833991e-05 -2.12765194e-05]
>>> exit()
```

I also have my LD_LIBRARY_PATH pointing to mujoco200. Here is a subset of my environement variables,

```
(spinningup) joehays@scylla:~$ env
SHELL=/bin/bash
CONDA_SHLVL=2
CONDA_PROMPT_MODIFIER=(spinningup) 
TERM_PROGRAM_VERSION=1.44.0
OLDPWD=/home/joehays/dev/spinningup
USER=joehays
LD_LIBRARY_PATH=/usr/lib/nvidia-440:/home/joehays/.mujoco/mujoco200/bin:
CONDA_PREFIX_1=/home/joehays/apps/miniconda
PATH=/home/joehays/apps/miniconda/envs/spinningup/bin:/home/joehays/apps/miniconda/condabin:/home/joehays/.vscode-server/bin/2aae1f26c72891c399f860409176fe435a154b13/bin:/usr/local/cuda-9.2/bin:/home/joehays/bin:/home/joehays/.local/bin:/home/joehays/.vscode-server/bin/2aae1f26c72891c399f860409176fe435a154b13/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
CONDA_PREFIX=/home/joehays/apps/miniconda/envs/spinningup
PWD=/home/joehays
CONDA_PYTHON_EXE=/home/joehays/apps/miniconda/bin/python
CONDA_DEFAULT_ENV=spinningup
```

I'm on the following system,

```
(spinningup) joehays@scylla:~$ cat /proc/version
Linux version 4.4.0-176-generic (buildd@lgw01-amd64-035) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12) ) #206-Ubuntu SMP Fri Feb 28 05:02:04 UTC 2020
```

and finally, here are the installed packages of my conda python 3.6 virtual environment,

```
(spinningup) joehays@scylla:~$ pip freeze
absl-py==0.9.0
astor==0.8.1
atari-py==0.2.6
attrs==19.3.0
backcall==0.1.0
box2d-py==2.3.8
certifi==2020.4.5.1
cffi==1.14.0
cloudpickle==1.2.1
cycler==0.10.0
Cython==0.29.16
decorator==4.4.2
fasteners==0.15
future==0.18.2
gast==0.2.2
glfw==1.11.0
google-pasta==0.2.0
grpcio==1.28.1
gym==0.15.7
h5py==2.10.0
imageio==2.8.0
importlib-metadata==1.6.0
ipython==7.13.0
ipython-genutils==0.2.0
jedi==0.17.0
joblib==0.14.1
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
kiwisolver==1.2.0
lockfile==0.12.2
Markdown==3.2.1
matplotlib==3.1.1
monotonic==1.5
more-itertools==8.2.0
mpi4py==3.0.3
mujoco-py==2.0.2.9
numpy==1.18.2
opencv-python==4.2.0.34
opt-einsum==3.2.0
packaging==20.3
pandas==1.0.3
parso==0.7.0
pexpect==4.8.0
pickleshare==0.7.5
Pillow==7.1.1
pluggy==0.13.1
prompt-toolkit==3.0.5
protobuf==3.11.3
psutil==5.7.0
ptyprocess==0.6.0
py==1.8.1
pycparser==2.20
pyglet==1.5.0
Pygments==2.6.1
pyparsing==2.4.7
pytest==5.4.1
python-dateutil==2.8.1
pytz==2019.3
scipy==1.4.1
seaborn==0.8.1
six==1.14.0
-e git+https://github.com/openai/spinningup.git@038665d62d569055401d91856abb287263096178#egg=spinup
tensorboard==1.15.0
tensorflow==1.15.2
tensorflow-estimator==1.15.1
termcolor==1.1.0
torch==1.3.1
tqdm==4.45.0
traitlets==4.3.3
wcwidth==0.1.9
Werkzeug==1.0.1
wrapt==1.12.1
zipp==3.1.0
```

I would greatly appreciate any insight as to why I get the error above when executing the prescribed `pip install 'gym[mujoco,robotics]'` command. 

Thank you.

**Comment by joehays** [comment] 2020-04-16 19:29
This appears to be very related to: 

https://github.com/openai/baselines/issues/1055

which is also still open/unresolved...

**Comment by joehays** [comment] 2020-04-16 19:48
Found the issue... the following note under the "What's New" section

```
2019-11-08 (v0.15.4)
Added multiple env wrappers (thanks @zuoxingdong and @hartikainen!)
Removed mujoco >= 2.0 support due to lack of tests
```

Validated by the following changelist:
https://github.com/openai/gym/commit/5fb359971a1f1fe384c2d9dcace130e577ec78bd#diff-2eeaed663bd0d25b7e608891384b7298

As a work around, clone gym and modify setup.py to allow for 2.0 and install from there...

**Comment by pengzhenghao** [comment] 2020-04-17 06:05
So we should use mujoco 1.5 in future?

That's quiet strange.. We use for mujoco 2.0 for years... We don't what exactly the baseline performance in previous papers when we keep changing version of gym / mujoco / mujoco-py..

By the way, in the README of mujoco-py they still recommend using mujoco 2.0, so that's mean the requirement of gym[mujoco] is different from mujoco-py ??

**Comment by christopherhesse** [comment] 2020-04-17 21:19
gym used to support both mujoco-py 2.0 and 1.5, but some users found issues with the upgrade: https://github.com/openai/gym/issues/1541

We have downgraded to only supporting 1.5 until results with mujoco-py 2.0 are verified to be the same.

Reproducibility of results is difficult because new versions are constantly released, so it would be nice if pinning the version of gym that you use for your experiments was sufficient, but that does not appear to be the case if we support both mujoco 1.5 and 2.0 at the same time.

You can workaround this by overriding setup.py, but please be aware that at least the issue I linked above exists.

**Comment by jkterry1** [comment] 2022-05-23 18:55
PR #2762 is about to be merged, introducing V4 MuJoCo environments using new bindings and a dramatically newer version of the engine. If this issue still persists with the V4 ones, please create a new issue for it.

**Closed by jkterry1** 2022-05-23 18:55 UTC
Labels: mujoco
