### ISSUE TITLE
MultiDiscrete flatten_space inconsistencies

### ISSUE THREAD

**Issue by rallen10** [openai/gym#2319] opened 2021-08-16 19:29 UTC
I ran into some seemingly glaring inconsistencies with [flattening](https://github.com/openai/gym/blob/bfd4f6d179c90c56356b7cd3bba323fdabd0d2d2/gym/spaces/utils.py#L103) a [MultiDiscrete space](https://github.com/openai/gym/blob/master/gym/spaces/multi_discrete.py)

1. `flatten_space(MultiDiscrete)` does __NOT__ behave the same as `flatten_space(Tuple([Discrete, Discrete]))`. Flattening a `Discrete` space results in a one-hot vector space. In turn, flattening a `Tuple([Discrete, Discrete])` results in a space of concatenated one-hot vectors. Therefore it would be expected that flattening a `MultiDiscrete` space would also result in a concatenated one-hot vectors space. This is __NOT__ the case. Instead `flatten_space(MultiDiscrete)` results in a space with the same dimensions as the original `MultiDiscrete` space with bounds drawn from the ranges of each variable in the original `MultiDiscrete` space. Therefore the flattening of `MultiDiscrete` has _almost_ no functional purpose; but it does seem to introduce a significant bug (see 2) 
2. `flatten_space(MultiDiscrete)` upper bound is invalid and causes invalid sample draws! The upper bound shouldn't be inclusive. This can be easily demonstrated with a simple `MultiDiscrete([2,2])` space:
```
from gym import spaces
a = spaces.MultiDiscrete([2,2])
valid_samples = [[0,0], [1,0], [0,1], [1,1]]

# this works
for i in range(100):
    sample = a.sample()
    assert list(sample) in valid_samples, "{} is not a valid sample of {}".format(flat_sample, valid_samples)

af = spaces.flatten_space(a)
# this will fail because a sample will be drawn with a value of 2 in one of the elements
for i in range(100):
    flat_sample = af.sample()
    assert list(flat_sample) in valid_samples, "{} is not a valid sample of {}".format(flat_sample, valid_samples)
```

See related thread [here](https://github.com/openai/gym/issues/1830), however inconsistency 2 was not identified nor was inconsistency 1 really addressed.

**Comment by jkterry1** [comment] 2021-08-16 19:33
Thanks for pointing this out. I believe that part of this is a duplicate of https://github.com/openai/gym/issues/1915, but ya the rest probably needs to be dealt with.

**Comment by jkterry1** [comment] 2021-08-21 02:49
I'm closing this in favor of the open PR so I can keep track of what all is going on

**Closed by jkterry1** 2021-08-21 02:49 UTC
Labels: PR Needed

**Comment by rallen10** [comment] 2021-08-21 17:28
Sounds good. Ignore the 'confused' reaction emoji on your previous comment. I accidentally clicked it and can't seem to remove it
