### ISSUE TITLE
Camera cannot track Agent

### ISSUE THREAD

**Issue by rawalkhirodkar** [openai/gym#1069] opened 2018-06-11 01:28 UTC
Mujoco: mjpro150
mujoco-py: master
gym: master

For the Mujoco agents (for eg Hopper-v2), the camera does not move with the agent, the agent moves out of the field of view. The camera shifts a little towards up with every start of a new episode.

Following is the log of self.viewer.cam.lookat for 10 episodes. x, y constant, z is added with 0.8 

> [-0.00416472  0.          1.1533927 ]
> [-0.00416472  0.          1.9533927 ]
> [-0.00416472  0.          2.7533927 ]
> [-0.00416472  0.          3.5533927 ]
> [-4.16471892e-03  0.00000000e+00  4.35339270e+00]
> [-4.16471892e-03  0.00000000e+00  5.15339270e+00]
> [-4.16471892e-03  0.00000000e+00  5.95339270e+00]
> [-4.16471892e-03  0.00000000e+00  6.75339270e+00]
> [-4.16471892e-03  0.00000000e+00  7.55339270e+00]
> [-4.16471892e-03  0.00000000e+00  8.35339270e+00]

I do reset the env after the start of each episode and the model xml files are untouched.
Any help is appreciated.
Thank you

**Comment by rajcscw** [comment] 2018-08-21 19:38
Any updates or work arounds for this @rawalkhirodkar ?

**Comment by R1ckF** [comment] 2018-08-27 12:43
Hi,
Any updates? When testing on Humanoid and Ant the same problem occurred. The camera is static and does not track the body when it moves out of the screen...

I did find a solution for the camera changing its angle and pointing towards the air. In envs/mujoco/hopper.py:

self.viewer.cam.lookat[2] += .8

should be:

self.viewer.cam.lookat[2] = .8

Apparently the camera is not affected by the env.reset() and therefore the camera keeps adding 0.8 at every simulation. It worked for me hope it does so for you as well. Would still like to know how to have the camera follow the body though ;)
Thx!

**Comment by christopherhesse** [comment] 2019-03-22 22:58
Closing as duplicate of https://github.com/openai/gym/issues/1135

**Closed by christopherhesse** 2019-03-22 22:58 UTC
