### ISSUE TITLE
Python3 Taxi-v1 Bugs

### ISSUE THREAD

**Issue by RuofanKong** [openai/gym#350] opened 2016-09-20 01:05 UTC
I'm training "Taxi-v1" with Python 3, and I notice that the action value "2" (Move East) and "3" (Move West) don't work at all, the taxi just stays at the point if it takes the action value "2" or "3". This works well for Python 2. I wonder if you could help to fix the issue. Thanks!

**Comment by tlbtlbtlb** [comment] 2016-09-20 01:39
Actions 2 and 3 work for me (transcript below). Are you sure it's in a state when it's legal to move east or west? If you're at the edge of the board or there's a barrier in the way it won't move, by design.

```python
gym$ python3
Python 3.5.2 (default, Sep  6 2016, 09:50:52)
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import gym
>>> e=gym.make('Taxi-v1')
[2016-09-19 18:35:22,189] Making new env: Taxi-v1
>>> e.reset()
53
>>> e.step(1)
(53, -1, False, {'prob': 1.0})
>>> e.step(2)
(73, -1, False, {'prob': 1.0})
>>> e.step(3)
(53, -1, False, {'prob': 1.0})
>>> e.step(4)
(53, -10, False, {'prob': 1.0})
>>>
```

**Comment by RuofanKong** [comment] 2016-09-20 01:41
I'm pretty sure action "2" and "3" doesn't work for me, and I noticed that you fixed some issue 12 days ago, and I'm curious if this is related to that fix.

**Comment by RuofanKong** [comment] 2016-09-20 01:52
Quick Update - OK. I found that my gym didn''t pick up the fix that you made 12 days ago, which caused the issue. I tried to do `pip install gym --upgrade`, but it didn't pick up this fix. So I tried `pip uninstall gym` and `pip install gym` again, it still didn't pick up the fix. So I wonder if there is something wrong in that part.

**Comment by tlbtlbtlb** [comment] 2016-09-20 03:44
Yes, you're right. It's fixed by https://github.com/openai/gym/commit/46b48a8a4a80ac86c487b7433e841e800abd9524, but that's not in PyPI yet. Until the next release, you can get the fix by installing from source:
```
git clone https://github.com/openai/gym.git
cd gym
pip install -e .
```

**Comment by RuofanKong** [comment] 2016-09-20 04:27
Thanks! also wonder when will be the next release :)

**Closed** 2019-04-01 05:35 UTC
