### ISSUE TITLE
CarRacing-v0 - Weird Camera Jerk Issue

### ISSUE THREAD

**Issue by praveenVnktsh** [openai/gym#2099] opened 2020-11-18 06:13 UTC
I noticed something weird when training my model on carracing-v0. Whenever a jerky braking situation is given, the camera flips vertically occasionally. Here is a picture of the same:

![flipped car](https://user-images.githubusercontent.com/30774147/99491692-340a8200-2992-11eb-997a-05a3f15a487a.png)

The left window shows the flipped image, and the one on the right is the frame previous to the current frame. The frame after the flipped frame is back to normal.

I noticed that there are a few odd lines in the environment's source file:

https://github.com/openai/gym/blob/c4d0af393ef9fba641bd3ebbbf1f60d291c8475d/gym/envs/box2d/car_racing.py#L421-L423

After some prodding, I noticed that occasionally the velocity of the car becomes negative as a result of which the atan function returns a negative number. The issue seems to be solved by commenting out those lines.

I do not understand the advantage of making the camera move with higher velocities since this can sometimes allow an agent to learn a lot more long range information by just having rapid movements. I observed this in some of my runs!

@olegklimov - Would be great if you could comment on this.

**Comment by carlosluis** [comment] 2021-12-12 18:57
I conducted a little experiment that confirms the sign switching problem reported by @praveenVnktsh 

Using this code 
```python
        if np.linalg.norm(vel) > 0.5:
            old_angle = ((angle + np.pi) % (2 * np.pi)) - np.pi  # normalize angle
            angle = math.atan2(vel[0], vel[1])
            if np.sign(old_angle) != np.sign(angle):
                print(f"old_angle = {old_angle}, new_angle = {angle}")
```
I then proceeded to steer the car recklessly until I see some angle flipping. Of course, near 0, pi and -pi, I see some angle flipping inherent from numerical approximations, but there's other instances where there's clearly a "wrong" angle flip

```
old_angle = 1.0416961908340454, new_angle = -1.2111190759830692
old_angle = 1.0416961908340454, new_angle = -1.2111190759830692
old_angle = 1.2610578536987305, new_angle = -1.1509918860429935
old_angle = 1.2610578536987305, new_angle = -1.1509918860429935
old_angle = 1.4788283109664917, new_angle = -1.1005596690570452
old_angle = 1.4788283109664917, new_angle = -1.1005596690570452
old_angle = 1.694751262664795, new_angle = -1.0476754974926226
old_angle = 1.694751262664795, new_angle = -1.0476754974926226
old_angle = 1.9067429304122925, new_angle = -0.9976619854163612
old_angle = 1.9067429304122925, new_angle = -0.9976619854163612
old_angle = 2.112739086151123, new_angle = -0.9519961141207258
```

The bug can also be visualized in the following gif:

<img src="https://user-images.githubusercontent.com/16105100/145725175-54f152f9-0924-4920-ad48-b3ee5d1c23ff.gif" width="50%" height="50%" />

If we comment out the lines suggested by @praveenVnktsh I cannot reproduce the visual jerk effect. In the following gif the angle seems consistent with the movement at all times

<img src="https://user-images.githubusercontent.com/16105100/145725255-a8a4461c-00c1-416c-90c0-8285c84f4d2d.gif" width="50%" height="50%" />

After playing around with this for a few minutes and without further context on why these lines were there in the first place, my recommendation would be to remove them. In a visual learning context, the current state of the environment is plain wrong and should be fixed

**Comment by jkterry1** [comment] 2021-12-12 19:42
@carlosluis 

A few questions:
- The observation space _is_ visual, right?
- What fixes to it should be made beyond the camera jerking? 
- This will require a version bump of the environment, right?

**Comment by carlosluis** [comment] 2021-12-12 20:17
1) Yes, the observation space is visual https://github.com/openai/gym/blob/180d8ddd5cce0d23cdc4cada1faa52f3ae45313c/gym/envs/box2d/car_racing.py#L145-L147
When I said "In a visual learning context, the current state of the environment is plain wrong" I was just pointing out that the image flip is a bug and shouldn't happen. I wasn't talking about the RL state, but the way the environment renders the next image/observation. 

2) Related to this specific problem, that would be the only fix AFAIK. The state of the environment is updated via the `render()` function, so fixing the wrong camera angle in `render()` automatically fixes the observation returned when doing `env.step`. This is the only opened issue related to `CarRacing`, so not sure there's anything else to fix right now unless there's some context I'm missing.

3) I didn't thought about that, but yes, I guess the change warrants bumping the version.

**Comment by jkterry1** [comment] 2021-12-13 01:54
Okay, so all that sounds good. Since we have to bump the version of car racing anyways, could you please redo the rendering in pygame as well in that PR? Right now other people are working on doing this for the classic control and the other 2 box2d environments, but I hadn't asked anyone to because I was expecting we were going to remove it. The motivation for pygame is that pyglet creates a bunch of huge headaches for installation and for headless rendering (which is very important on servers). The advantage of doing this all at once is that this update would require a version bump for car racing since the observation space is graphical, so I'm trying to do everything all at once.

**Closed** 2021-12-30 22:27 UTC
Labels: help wanted
