### ISSUE TITLE
Mujoco 1.50 support

### ISSUE THREAD

**Issue by ViktorM** [openai/gym#668] opened 2017-07-27 08:32 UTC
Hi,

Can you provide some estimates when support of Mujoco 1.50 will be added to the Gym? This version was released quit long ago - in April.

**Comment by gautam1858** [comment] 2017-08-01 05:26
+1

**Comment by koulanurag** [comment] 2017-08-01 07:29
+1

**Comment by Carmezim** [comment] 2017-08-06 13:32
Duplicate of #638

**Comment by wenyeming333** [comment] 2017-08-23 01:05
+1

**Comment by tartavull** [comment] 2017-09-02 19:28
+1

**Comment by christopherhesse** [comment] 2019-05-24 22:28
Closing in favor of https://github.com/openai/gym/issues/638

**Closed by christopherhesse** 2019-05-24 22:28 UTC
