### ISSUE TITLE
AttributeError: 'TimeLimit' object has no attribute 'x_threshold' 

### ISSUE THREAD

**Issue by jake-sanvito** [openai/gym#876] opened 2018-02-09 16:43 UTC
I am trying to run the basic pytorch tutorial on RL. I cannot seem to get past this error. I realize that it was supposed to have been fixed but evidently not for me:

`AttributeError                            Traceback (most recent call last)
<ipython-input-8-3aa424675ed4> in <module>()
     38 env.reset()
     39 plt.figure()
---> 40 plt.imshow(get_screen().cpu().squeeze(0).permute(1, 2, 0).numpy(),
     41            interpolation='none')
     42 plt.title('Example extracted screen')

<ipython-input-8-3aa424675ed4> in get_screen()
     19     screen = screen[:, 160:320]
     20     view_width = 320
---> 21     cart_location = get_cart_location()
     22     if cart_location < view_width // 2:
     23         slice_range = slice(view_width)

<ipython-input-8-3aa424675ed4> in get_cart_location()
      8 
      9 def get_cart_location():
---> 10     world_width = env.x_threshold * 2
     11     scale = screen_width / world_width
     12     return int(env.state[0] * scale + screen_width / 2.0)  # MIDDLE OF CART

AttributeError: 'TimeLimit' object has no attribute 'x_threshold'

<matplotlib.figure.Figure at 0x7efdf8b3fe80>
`

**Comment by christopherhesse** [comment] 2019-07-26 21:51
Closing as a duplicate of https://github.com/openai/gym/issues/877

**Closed by christopherhesse** 2019-07-26 21:51 UTC
