### ISSUE TITLE
Behaviors of Atari envs have changed by atari-py>=0.2

### ISSUE THREAD

**Issue by muupan** [openai/gym#1777] opened 2020-01-05 09:50 UTC
The behaviors of Atari envs seem affected by the version of `atari-py` even though the env id the same.

```python
import gym

env = gym.make('MsPacmanNoFrameskip-v4')
env.seed(0)
env.reset()
done = False
t = 0
R = 0
while not done:
    _, r, done, _ = env.step(1)
    t += 1
    R += r
print(t, R)
```
Below is the output of this code for each pair of `gym` and `atari-py`. It seem like `atari-py` is the cause of the difference, but since `gym` requires `atari-py~=0.2.0` in `setup.py` from 1.3.0 (https://github.com/openai/gym/pull/1535) it should be responsible for the version of `atari-py`. That is why I opened this issue here, not in https://github.com/openai/atari-py.
- `gym==0.15.4` `atari-py==0.2.6`: 2009 90.0
- `gym==0.15.4` `atari-py==0.2.0`: 2009 90.0
- `gym==0.15.4` `atari-py==0.1.15`: 1329 90.0
- `gym==0.15.4` `atari-py==0.1.4`: 1329 90.0
- `gym==0.12.6` `atari-py==0.2.6`: 2009 90.0
- `gym==0.12.6` `atari-py==0.2.0`: 2009 90.0
- `gym==0.12.6` `atari-py==0.1.15`: 1329 90.0
- `gym==0.12.6` `atari-py==0.1.4`: 1329 90.0

I also confirmed such a difference for `ChopperCommandNoFrameskip-v4`.

I am concerned that these differences might significantly affect the evaluation of RL algorithms. Has anyone investigated the effect?

**Comment by muupan** [comment] 2020-01-06 03:01
Below are the results obtained by my PPO implementation on Atari using 3 different seeds for each configuration. `gym==0.12.1` was used. It seems that it actually affect the performance for some games. I'm not sure what change in atari-py or ALE caused this though.

![image](https://user-images.githubusercontent.com/815970/71792164-f7d07a80-307a-11ea-92c1-a4d15a63cb41.png)
![image](https://user-images.githubusercontent.com/815970/71792174-ff901f00-307a-11ea-9af2-437c9bcab8ce.png)
![image](https://user-images.githubusercontent.com/815970/71792179-09198700-307b-11ea-8b1e-53c11b8fd62a.png)

**Comment by kngwyu** [comment] 2020-01-06 11:19
https://github.com/openai/atari-py/pull/49 looks the biggest change

**Comment by christopherhesse** [comment] 2020-01-10 23:27
The changes were meant specifically to not change the behavior of the environments: https://github.com/openai/atari-py/pull/49#issuecomment-495732015

@JesseFarebro any idea what might be going on here?

**Comment by christopherhesse** [comment] 2020-01-10 23:28
Thanks for investigating this @muupan

**Comment by JesseFarebro** [comment] 2020-01-11 00:27
Hi @muupan @christopherhesse,

Thanks for bringing this to my attention. I'll investigate further and let you know what my findings are.

**Comment by JesseFarebro** [comment] 2020-01-11 03:07
Thanks for the reproduction @muupan.

With regards to **Ms. Pacman**: Essentially what is happening is once you press the select button too many times the game just begins. We press the select button in order to select modes and difficulties. The following commit introduced this bug: https://github.com/mgbellemare/Arcade-Learning-Environment/commit/7bff96b4b64edcffbeb2d9bb83b1685ab506ea2b#diff-d9d868097a7403416e6ef352d95dc4feR85. I will open an issue upstream and see what can be done about this. This should have minimal effects on performance comparisons between `v0.5.2` and `v0.6.*`. This bug makes it so there would be different episode starting locations. Here are two images, each contains the first frame between versions `v0.5.2` and `v0.6.0`.

### Ms. Pacman v0.5.2
![frame-v0 5 2](https://user-images.githubusercontent.com/1377567/72197909-ddccca00-33e3-11ea-9a90-a7667456eabb.png)
### Ms. Pacman v0.6.0
![frame-v0 6 0](https://user-images.githubusercontent.com/1377567/72197911-e1605100-33e3-11ea-9624-4ad969bd1aad.png)


With regards to **Chopper Command**: The issue that affects Ms. Pacman also affects Chopper Command. The call to `softReset` happens in two places. The one linked above and also https://github.com/mgbellemare/Arcade-Learning-Environment/commit/31d8e17f404ead5c84cef834f7323a24226003cb#diff-0ff5bae3de90143156577bc8324e6d27R155.

As for the performance difference in your PPO agent that doesn't actually strike me as overly surprising. If we assume that these two runs weren't completely deterministic (due to a different episode starting point as discussed above, or an improper seed) these curves seem within reason for 3 seeds. I looked at the original PPO paper and their results on Chopper Command show large variance between runs their 3 runs.

I'll post these issues upstream along with your learning curves and we'll see what @mgbellemare and @mcmachado think. I'm not too familiar with the `v0.5.2` -> `v0.6.0` code so maybe they can provide more insight on the `softReset()` calls. 

Hopefully, this helps clear some things up.

**Comment by christopherhesse** [comment] 2020-01-17 23:00
Thanks for investigating @JesseFarebro!

**Comment by JesseFarebro** [comment] 2021-08-05 04:55
This is being tracked upstream https://github.com/mgbellemare/Arcade-Learning-Environment/issues/291. Feel free to close this.

**Closed** 2021-08-05 05:13 UTC
Labels: help wanted
