### ISSUE TITLE
DoomDeathmatch environment crashes sporadically

### ISSUE THREAD

**Issue by jietang** [openai/gym#167] opened 2016-06-10 00:32 UTC
https://travis-ci.org/openai/gym/jobs/136575858

**Comment by jietang** [comment] 2016-06-10 00:32
@ppaquette can you take a look?

**Comment by ppaquette** [comment] 2016-06-10 20:11
That's an interesting bug

- I also get 15 errors (ViZDoomErrorException: Controlled ViZDoom instance reported error) when I run nose2 on my computer (when game.init() is called)
- I have only seen those errors while running unit tests.
- The make_action() VizDoomErrorException is usually triggered after a *** Fatal Error *** Address not mapped to object (signal 11) // Address: 0x278 // Generating vizdoom-crash.log and killing process 15103, please wait... sh: 1: gdb: not found (The job you provided has this error in the middle of the page)

[vizdoom-crash-1.txt](https://github.com/openai/gym/files/309681/vizdoom-crash-1.txt)
[vizdoom-crash-2.txt](https://github.com/openai/gym/files/309682/vizdoom-crash-2.txt)

- VizDoomErrorException simply means FreeDoom has crashed, but the reason is unknown
- My game.init() exceptions seem to be related to the inter-process communication between the VizDoom instance and FreeDoom (through shared memory and message queuing).
- We probably need to file an upstream bug and get the underlying FreeDoom error to properly debug.
- I'm having the feeling that the VizDoom instance id is shared across all unit tests, and that makes the IPC constructor fail on game.init() when a previous VizDoom instance has been terminated. The game.make_action() seems to fail because of the fatal error (i.e. FreeDoom crash)

**Comment by ppaquette** [comment] 2016-06-11 12:03
### Problem 1 - VizDoom crashes with Fatal Error - Address not mapped to object (signal 11) on game.make_action()

Caused by: - /gym/spaces/discrete.py - Line 13
```python
    def sample(self):
        return prng.np_random.randint(self.n)
```
Any call to prng in that specific method creates the error. I don't fully understand why, but I can reproduce the bug consistently.

The sample() method is called from 
- /gym/envs/tests/test_determinism.py - Line 38 - (env2.action_space.sample() for i in range(4))
- the problem only appears when the 'Hex9x9-v0' is being tested in test_determinism

Fixed with:
```python
    def sample(self):
        # prng is terminating VizDoom with Fatal Error - Address not mapped to object (signal 11)
        # 82 is for HexEnv (9x9), which is the environment causing the Vizdoom crash
        if 82 == self.n: return int(round(time.time(), -1) % self.n)
        return prng.np_random.randint(self.n)
```

 
### Problem 2 - VizDoom triggers VizDoomErrorException on game.init() for all missions

Caused by: - /gym/envs/board_game/go.py - Line 215 (self.state.act(action))
```python
        try :
            # Problem line
            self.state = self.state.act(action)
        except pachi_py.IllegalMove:
            if self.illegal_move_mode == 'raise':
                six.reraise(*sys.exc_info())
            elif self.illegal_move_mode == 'lose':
                # Automatic loss on illegal move
                self.done = True
                return self.state.board.encode(), -1., True, {'state': self.state}
            else:
                raise error.Error('Unsupported illegal move action: {}'.format(self.illegal_move_mode))
```

- This line is called by test_determinism, and then triggers an error that is supposed to be catched
- After the pachi_py.IllegalMove error has been raised, VizDoom generates VizDoomErrorException on any game.init() called

Proposed Workaround:
- Modify pachi_py to return a boolean that indicates if move would be valid
```python
is_valid_move = self.state.check_if_valid(action)
if is_valid_move:
    self.state = self.state.act(action)
else:
    # Handle error
```

**Comment by jietang** [comment] 2016-06-13 18:30
Very interesting, thanks for the detective work (and workarounds). 

I'd love to dig in more and understand the mechanism that's triggering these crashes. Otherwise it will be brittle and likely to crash down the line

**Comment by jietang** [comment] 2016-07-21 01:02
@ppaquette, is this still an issue after your doom fixes?

**Closed** 2016-08-22 20:45 UTC
