### ISSUE TITLE
Feature request: observation space rescale wrapper

### ISSUE THREAD

**Issue by hartikainen** [openai/gym#1939] opened 2020-06-04 12:29 UTC
It would be great to have a `RescaleObservation`-wrapper similar to the existing [RescaleAction](https://github.com/openai/gym/blob/d8908cbf101c253ea9b4fb0858f1e90d899b6596/gym/wrappers/rescale_action.py#L7)-wrapper.

The observation spaces can generally be unbounded, so it should verify that the `observation_space.{low,high}` are finite and throw an error if that's not the case.

**Comment by justinkterry** [comment] 2020-08-09 16:48
There's a library that includes all standard wrappers for Gym environments, including this:

https://github.com/PettingZoo-Team/SuperSuit

**Comment by jkterry1** [comment] 2021-07-30 20:01
@ryannavillus

**Comment by jkterry1** [comment] 2021-08-21 02:38
Duplicate of #2283 and plans described in the current wrapper docs

**Closed by jkterry1** 2021-08-21 02:38 UTC
Labels: help wanted
