### ISSUE TITLE
[Bug] Numpy raises TypeError in passive_env_checker

### ISSUE THREAD

**Issue by Trezorro** [openai/gym#2876] opened 2022-06-10 09:38 UTC
The observation that needs to be returned by env.step() needs to be of the standard dict type. In the code line linked below, this object is checked for nan's in an invalid way :
https://github.com/openai/gym/commit/134de4a713079053fd6d2277adf2ed4326e9856b#r75779776

This line causes numpy to raise a TypeError that is not caught:
```
TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe'' 
```

**Comment by pseudo-rnd-thoughts** [comment] 2022-06-10 10:00
Thanks for the issue @Trezorro, we can't replicate your issue.
Could you provide the code you used to cause the issue

```python
>>> import gym
>>> env = gym.make("CartPole-v1")
>>> env.reset()
>>> env.step(0)
(array([-0.0217819 , -0.04622297, -0.05363911, -0.03604983], dtype=float32), 1.0, False, {})
```

**Comment by RedTachyon** [comment] 2022-06-11 21:06
My understanding of the issue is that the line `if np.any(np.isnan(obs)):` in the env checker assumes that the observation is a numpy array, while it could be... anything pretty much, including a dictionary under the built-in Dict space.

**Comment by ikostrikov** [comment] 2022-06-12 06:44
I'm experiencing the same issue with environments converted from dm_control that have `Dict` observation space.

**Comment by pseudo-rnd-thoughts** [comment] 2022-06-12 10:36
@ikostrikov Thanks, I have fixed this bug in #2873

**Comment by pseudo-rnd-thoughts** [comment] 2022-06-13 09:18
@Trezorro and @ikostrikov Would both of you be able to run this PR with your environments to check that the error doesn't happen anymore https://github.com/openai/gym/pull/2873

**Comment by BlueskyFR** [comment] 2022-06-22 19:27
@pseudo-rnd-thoughts your PR was closed and I don't see the one fixing this issue anymore, which one is it now?

**Comment by ikostrikov** [comment] 2022-06-28 02:53
@pseudo-rnd-thoughts  Sorry for the delay, yes, the fix works for me. Thanks a lot!

**Comment by epignatelli** [comment] 2022-06-30 14:04
What is the status of the issue?
Did anyone `git bisect` this?

The breaking change affects also environments outside this repository.

**Comment by epignatelli** [comment] 2022-06-30 14:38
Thanks for the heads up @RedTachyon.

**Comment by jkterry1** [comment] 2022-07-06 13:17
Closing in favor of #2903

**Closed by jkterry1** 2022-07-06 13:17 UTC
