### ISSUE TITLE
pyglet.gl.lib.GLException: invalid value

### ISSUE THREAD

**Issue by krishnadots** [openai/gym#397] opened 2016-10-29 08:56 UTC
Hi,

I have installed the full version of open AI gym after installing the necessary pre-requisites, as mentioned on the gym github page. My machine runs Ubuntu 14.04. When I try to run one of the examples on the docs page, (e.g CartWheel), I get the following error.  Following the suggestion in a related  issue, I tried glxinfo and glxgears and both of them work. I would appreciate your help in finding a fix. The pyglet version is 1.2.4, which was installed as part of the full gym installation.

Thanks.

Making new env: CartPole-v0
Traceback (most recent call last):
  File "cart_pole.py", line 15, in <module>
    env.render()
  File "/usr/local/lib/python2.7/dist-packages/gym/core.py", line 192, in render
    return self._render(mode=mode, close=close)
  File "/usr/local/lib/python2.7/dist-packages/gym/envs/classic_control/cartpole.py", line 149, in _render
    return self.viewer.render(return_rgb_array = mode=='rgb_array')
  File "/usr/local/lib/python2.7/dist-packages/gym/envs/classic_control/rendering.py", line 84, in render
    self.window.dispatch_events()
  File "/usr/local/lib/python2.7/dist-packages/pyglet/window/xlib/__init__.py", line 840, in dispatch_events
    self.dispatch_pending_events()
  File "/usr/local/lib/python2.7/dist-packages/pyglet/window/xlib/**init**.py", line 880, in dispatch_pending_events
    EventDispatcher.dispatch_event(self, _self._event_queue.pop(0))
  File "/usr/local/lib/python2.7/dist-packages/pyglet/event.py", line 365, in dispatch_event
    if getattr(self, event_type)(_args):
  File "/usr/local/lib/python2.7/dist-packages/pyglet/window/**init**.py", line 722, in on_resize
    gl.glOrtho(0, width, 0, height, -1, 1)
  File "/usr/local/lib/python2.7/dist-packages/pyglet/gl/lib.py", line 104, in errcheck
    raise GLException(msg)
pyglet.gl.lib.GLException: invalid value

**Comment by tlbtlbtlb** [comment] 2017-03-15 20:37
Closing for lack of detail.

**Closed by tlbtlbtlb** 2017-03-15 20:37 UTC

**Comment by JacobianTang** [comment] 2017-03-21 09:13
I also have this problem

**Comment by tlbtlbtlb** [comment] 2017-03-21 16:55
Could you provide enough detail so that we could reproduce the problem?

**Comment by linxiamen** [comment] 2017-03-22 02:36
I also got this problem.And here is what my python file is:

import numpy as np
import tensorflow as tf
import gym
import pyglet
env = gym.make('CartPole-v0')

env.reset()
random_episodes = 0
reward_sum = 0
while random_episodes < 10:
    env.render()
    observation,reward,done,_=env.step(np.random.randint(0,2))
    reward_sum+=reward
    if done:
        random_episodes+=1
        print "Reward for this episode was: ",reward_sum
        reward_sum=0
        env.reset()

And when I ran the line "env.render()",I got the message as follows:
[2017-03-22 10:18:11,379] Making new env: CartPole-v0
Traceback (most recent call last):
  File "DRL.py", line 11, in <module>
    env.render()
  File "/home/carc/anaconda2/lib/python2.7/site-packages/gym/core.py", line 175, in render
    return self._render(mode=mode, close=close)
  File "/home/carc/anaconda2/lib/python2.7/site-packages/gym/envs/classic_control/cartpole.py", line 149, in _render
    return self.viewer.render(return_rgb_array = mode=='rgb_array')
  File "/home/carc/anaconda2/lib/python2.7/site-packages/gym/envs/classic_control/rendering.py", line 84, in render
    self.window.dispatch_events()
  File "/home/carc/anaconda2/lib/python2.7/site-packages/pyglet/window/xlib/__init__.py", line 840, in dispatch_events
    self.dispatch_pending_events()
  File "/home/carc/anaconda2/lib/python2.7/site-packages/pyglet/window/xlib/__init__.py", line 880, in dispatch_pending_events
    EventDispatcher.dispatch_event(self, *self._event_queue.pop(0))
  File "/home/carc/anaconda2/lib/python2.7/site-packages/pyglet/event.py", line 365, in dispatch_event
    if getattr(self, event_type)(*args):
  File "/home/carc/anaconda2/lib/python2.7/site-packages/pyglet/window/__init__.py", line 722, in on_resize
    gl.glOrtho(0, width, 0, height, -1, 1)
  File "/home/carc/anaconda2/lib/python2.7/site-packages/pyglet/gl/lib.py", line 104, in errcheck
    raise GLException(msg)
pyglet.gl.lib.GLException: invalid value
My pyglet version is 1.2.4 and gym  is 0.7.0.I also ran glxinfo and it seemed worked well.My machine also runs Ubuntu 14.04.Any suggestion would be greatly appreciated!

**Comment by linxiamen** [comment] 2017-03-22 02:45
I also got this problem.And here is what my python file is:

import numpy as np
import tensorflow as tf
import gym
import pyglet
env = gym.make('CartPole-v0')

env.reset()
random_episodes = 0
reward_sum = 0
while random_episodes < 10:
    env.render()
    observation,reward,done,_=env.step(np.random.randint(0,2))
    reward_sum+=reward
    if done:
        random_episodes+=1
        print "Reward for this episode was: ",reward_sum
        reward_sum=0
        env.reset()

My pyglet version is 1.2.4 and gym  is 0.7.0.My machine also runs Ubuntu 14.04.I also ran glxinfo and it seemed not worked well.And here is the message:
$ glxinfo
name of display: :1
Warning: GL error 0x500 at line 922
display: :1  screen: 0
direct rendering: No (If you want to find out why, try setting LIBGL_DEBUG=verbose)
server glx vendor string: SGI
server glx version string: 1.2
server glx extensions:
    GLX_EXT_import_context, GLX_EXT_visual_info, GLX_EXT_visual_rating
client glx vendor string: NVIDIA Corporation
client glx version string: 1.4

Any suggestion would be greatly appreciated!

**Comment by qq456cvb** [comment] 2018-03-02 06:51
Finally, I found a work-around. The issue is related to glOrtho function in **[your-python-site-packages]/pyglet/window/__init__.py**. I modified **BaseWindow**'s _on_resize_ function to the following:
```
viewport = self.get_viewport_size()
# wierd factor 2
gl.glViewport(-viewport[0], -viewport[1], max(1, viewport[0]*2), max(1, viewport[1]*2))
gl.glMatrixMode(gl.GL_PROJECTION)
gl.glLoadIdentity()
# wierd factor 2
r = max(1.0,width*2)
l = 0.0
t = max(1.0,height*2)
b = 0.0
f = 1.0
n = -1.0
# replace glOrtho with equivalent matrix operations
gl.glScaled(2.0/(r-l),2.0/(t-b),-2.0/(f-n))
gl.glTranslated(-(r+l)/(r-l), -(t+b)/(t-b), -(f+n)/(f-n))
# gl.glOrtho(ctypes.c_double(0), ctypes.c_double(800), ctypes.c_double(0), ctypes.c_double(600), ctypes.c_double(-1), ctypes.c_double(1)) ## comment out this line which raises Exception
gl.glMatrixMode(gl.GL_MODELVIEW)
```
What I did is to just replace **glOrtho** with its equivalent matrix operations. Besides, I modified **glViewport** which is wierd but works. A possible cause of this problem might be that, on cpp side, arguments are interpreted differently from what they are on python side. But I am not sure anyway.
