### ISSUE TITLE
Openai headless.

### ISSUE THREAD

**Issue by abhigenie92** [openai/gym#883] opened 2018-02-12 00:00 UTC
I am trying to record the video of env, on machine I have sshed to.
Code:
```
import gym
from gym import wrappers
env = gym.make("CartPole-v1")
env = wrappers.Monitor(env, "./try/", force = True)
for i_episode in range(20):
    observation = env.reset()
for t in range(100):
    print(observation)
    action = env.action_space.sample()
    observation, reward, done, info = env.step(action)
    if done:
        print("Episode finished after {} timesteps".format(t+1))
        break
```
Error:
```
python check_code.py
No protocol specified
Traceback (most recent call last):
  File "check_code.py", line 7, in <module>
    observation = env.reset()
  File "/nohome/jaan/abhishek/anaconda3/lib/python3.6/site-packages/gym/core.py", line 104, in reset
    return self._reset()
  File "/nohome/jaan/abhishek/anaconda3/lib/python3.6/site-packages/gym/wrappers/monitoring.py", line 41, in _reset
    self._after_reset(observation)
  File "/nohome/jaan/abhishek/anaconda3/lib/python3.6/site-packages/gym/wrappers/monitoring.py", line 198, in _after_reset
    self._reset_video_recorder()
  File "/nohome/jaan/abhishek/anaconda3/lib/python3.6/site-packages/gym/wrappers/monitoring.py", line 219, in _reset_video_recorder
    self.video_recorder.capture_frame()
  File "/nohome/jaan/abhishek/anaconda3/lib/python3.6/site-packages/gym/monitoring/video_recorder.py", line 106, in capture_frame
    frame = self.env.render(mode=render_mode)
  File "/nohome/jaan/abhishek/anaconda3/lib/python3.6/site-packages/gym/core.py", line 150, in render
    return self._render(mode=mode, close=close)
  File "/nohome/jaan/abhishek/anaconda3/lib/python3.6/site-packages/gym/core.py", line 286, in _render
    return self.env.render(mode, close)
  File "/nohome/jaan/abhishek/anaconda3/lib/python3.6/site-packages/gym/core.py", line 150, in render
    return self._render(mode=mode, close=close)
  File "/nohome/jaan/abhishek/anaconda3/lib/python3.6/site-packages/gym/envs/classic_control/cartpole.py", line 115, in _render
    from gym.envs.classic_control import rendering
  File "/nohome/jaan/abhishek/anaconda3/lib/python3.6/site-packages/gym/envs/classic_control/rendering.py", line 23, in <module>
    from pyglet.gl import *
  File "/nohome/jaan/abhishek/anaconda3/lib/python3.6/site-packages/pyglet/gl/__init__.py", line 239, in <module>
    import pyglet.window
  File "/nohome/jaan/abhishek/anaconda3/lib/python3.6/site-packages/pyglet/window/__init__.py", line 1884, in <module>
    gl._create_shadow_window()
  File "/nohome/jaan/abhishek/anaconda3/lib/python3.6/site-packages/pyglet/gl/__init__.py", line 208, in _create_shadow_window
    _shadow_window = Window(width=1, height=1, visible=False)
  File "/nohome/jaan/abhishek/anaconda3/lib/python3.6/site-packages/pyglet/window/xlib/__init__.py", line 166, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/nohome/jaan/abhishek/anaconda3/lib/python3.6/site-packages/pyglet/window/__init__.py", line 501, in __init__
    display = get_platform().get_default_display()
  File "/nohome/jaan/abhishek/anaconda3/lib/python3.6/site-packages/pyglet/window/__init__.py", line 1833, in get_default_display
    return pyglet.canvas.get_display()
  File "/nohome/jaan/abhishek/anaconda3/lib/python3.6/site-packages/pyglet/canvas/__init__.py", line 82, in get_display
    return Display()
  File "/nohome/jaan/abhishek/anaconda3/lib/python3.6/site-packages/pyglet/canvas/xlib.py", line 86, in __init__
    raise NoSuchDisplayException('Cannot connect to "%s"' % name)
pyglet.canvas.xlib.NoSuchDisplayException: Cannot connect to "None"
```
I followed instructions from here https://github.com/2017-fall-DL-training-program/Setup_tutorial/blob/master/OpenAI-gym-install.md

Anydesk gives me the following error:
```
anydesk
No protocol specified

(anydesk:19087): Gtk-WARNING **: cannot open display: :0
No protocol specified

(anydesk:19089): Gtk-WARNING **: cannot open display: :0
No protocol specified

```

**Comment by jamsawamsa** [comment] 2018-02-15 06:23
bump, having the same issue here

**Comment by josiahls** [comment] 2019-04-27 22:19
I am having the same issue. I call render("rgb_array") and it still loads the env window. This seems like an obvious thing that we would want to avoid. I am using pybullet3 which is a full physics engine, and even that has easy headless rendering

**Comment by christopherhesse** [comment] 2019-07-26 21:49
This looks like a duplicate of https://github.com/openai/gym/issues/366.  The best fix on the gym side would be to support EGL, but it looks like pyglet does not support that yet: https://github.com/openai/gym/issues/1338

**Closed by christopherhesse** 2019-07-26 21:49 UTC
