### ISSUE TITLE
[Bug Report] KeyError: (<weakref at 0x00000185FF878EA8; to 'Win32Window' at 0x00000185FF878EA8>,)

### ISSUE THREAD

**Issue by zbeucler2018** [openai/gym#2768] opened 2022-04-21 17:32 UTC
**Describe the bug**
Hello! I am trying to run a Gym retro environment on my windows 10 machine. I decided to make this issue in the Gym repo because that is where the error occurs. Here is the error

Let me know if anymore info is needed.

```
Exception ignored in <bound method SimpleImageViewer.__del__ of <gym.envs.classic_control.rendering.SimpleImageViewer object at 0x00000185FC3D4CF8>>
Traceback (most recent call last):
File "C:\Users\Me\Desktop\Final\env\lib\site-packages\gym\envs\classic_control\rendering.py", line 458, in __del__ self.close()
File "C:\Users\Me\Desktop\Final\env\lib\site-packages\gym\envs\classic_control\rendering.py", line 454, in close self.window.close()
File "C:\Users\Me\Desktop\Final\env\lib\site-packages\pyglet\window\win32\__init__.py", line 336, in close super(Win32Window, self).close()
File "C:\Users\Me\Desktop\Final\env\lib\site-packages\pyglet\window\__init__.py", line 857, in close app.windows.remove(self)
File "C:\Users\Me\AppData\Local\Programs\Python36\lib\_weakrefset.py", line 109, in remove  self.data.remove(ref(item))
KeyError: (<weakref at 0x00000185FF878EA8; to 'Win32Window' at 0x00000185FF878EA8>,)
```

**Code example**
```python3
import retro
env = retro.make("SuperMarioKart-Snes")
obs = env.reset()
running = True
actionSpace = getAction()
i = 0
frames = 0
while running:
    obs, reward, isDone, info = env.step(actionSpace)
    i += 1
    frames += 1
    env.render()
    if(frames == len(actionSpace)-1):
        running == False
env.close()
```

**System Info**
 * Gym (and gym-retro) installed via Pip
 * Windows 10
 * Python version 3.6
 * Most up-to-date Gym version

**Additional context**
- Found this issue [here](https://github.com/openai/gym/issues/2696) which had the same problem but was closed because it was stale.

### Checklist

- [x] I have checked that there is no similar (open) [issue](https://github.com/openai/gym/issues) in the repo

**Comment by RedTachyon** [comment] 2022-04-21 21:29
`retro` isn't really supported or maintained anymore. My guess is that if you really want it to work, you'll need to downgrade to some older version of `gym` (which, in contrast, is maintained), but it's unlikely you'll be able to get much help on that.

**Comment by jkterry1** [comment] 2022-04-29 22:33
Closing as this is for a different library. You might want to look at stable-retro through.

**Closed by jkterry1** 2022-04-29 22:33 UTC

**Comment by zbeucler2018** [comment] 2022-06-04 01:41
I found the source of the error for future reference. My code was basically creating an environment and closing it very very fast. Hope this helps someone in the future!

```
import gym
while True:
   env = gym.make("LunarLander-v2")
   env.reset()
   ...
   env.close()
```

**Comment by pseudo-rnd-thoughts** [comment] 2022-06-05 15:18
@zbeucler2018 Im not able to replicate your issue on mac, 3.9 and v24
```python
import gym
for _ in range(20):
    env = gym.make("LunarLander-v2", disable_env_checker=True)
    env.reset()
    env.render()

    env.close()
```

What OS, python version and gym version are you using?

**Comment by TheMedicineSeller** [comment] 2023-01-02 14:59
I'm neither making an env every iteration nor destroying it, but I still get the same error after roughly about 1400 steps every time i run this script..
`
def main():
    env = retro.make("Airstriker-Genesis")
    env = TimeLimitWrapper(env)
    env = MaxAndSkipEnv(env, 4)
    obs = env.reset()
    done = False

    steps = 0
    while not done:
        action, state = model.predict(obs)
        obs, rewards, done, info = env.step(action)
        env.render()
        if done:
            steps += 1
        if steps % 1000 == 0:
            print(f"Total steps: {steps}")
            print(info)

        print("Final info:")
        print(info)
    env.close()

if __name__ == "__main__":
    model = PPO.load("temp/best_model.zip")
    main()
`

Python version is 3.9 and gym version is 0.21.0, windows 10 OS.

**Comment by pseudo-rnd-thoughts** [comment] 2023-01-02 17:53
Could you clarify what the error is?

**Comment by TheMedicineSeller** [comment] 2023-01-03 05:39
@pseudo-rnd-thoughts 

![image](https://user-images.githubusercontent.com/87657352/210304767-1364a653-f0cf-4d85-a103-9be28b425bcf.png)

This is the error, it happens around 1300 - 1400 timesteps in

**Comment by pseudo-rnd-thoughts** [comment] 2023-01-03 12:58
This is for Gym v0.21 which is not longer maintained but I suspect that the issue is that somehow you are recreating the environment but the original environment has not been closed correctly or the original environment has not been created correctly.
The exact error is that the element `ref(item)` doesn't exist in `self.data` a dictionary object anymore. 
Why? Im not sure. Sorry I can't be more help

**Comment by TheMedicineSeller** [comment] 2023-01-03 14:40
But i'm not creating an environment every iteration .. neither closing one.

> This is for Gym v0.21 which is not longer maintained

Ah so has all the work shifted to [gymnasium](https://github.com/Farama-Foundation/Gymnasium).

**Comment by pseudo-rnd-thoughts** [comment] 2023-01-03 15:30
> Ah so has all the work shifted to [gymnasium](https://github.com/Farama-Foundation/Gymnasium).

Yes and no more v0.21 releases are planned.

> But i'm not creating an environment every iteration .. neither closing one.

Are you sure because in the example code above (https://github.com/openai/gym/issues/2768#issuecomment-1369012393) you include `env.close()` at the end with the example only run once while in the figure (https://github.com/openai/gym/issues/2768#issuecomment-1369411361), it shows `final info: ...` which in the example only happens when `done=True`

**Comment by becky3** [comment] 2024-05-12 04:37
I know this is somewhat late, 
but I encountered a similar issue while working with Gym Retro. 

In my case, I was getting a similar error when the game was ending.

However, calling the following just before `env.close()` resolved the error:

```python
env.render(close=True)
```

I wanted to report this as a reference.
