### ISSUE TITLE
Mujoco 

### ISSUE THREAD

**Issue by gautam1858** [openai/gym#665] opened 2017-07-25 05:24 UTC
Hi, Can we get support for Mujoco 1.5 version because the new MacBook doesn't support 1.3 version ?

**Comment by ViktorM** [comment] 2017-07-26 18:13
The same request. I'm working with Mujoco 1.5 on Windows and can't downgrade it to 1.3 to use it with gym.

**Comment by Carmezim** [comment] 2017-08-06 13:31
Duplicate of #638

**Comment by christopherhesse** [comment] 2019-09-27 22:08
Closed as a duplicate.

**Closed by christopherhesse** 2019-09-27 22:08 UTC
