### ISSUE TITLE
When Running env(FetchPickAndPlace-v0), Missing GL version problem

### ISSUE THREAD

**Issue by xhzcyc** [openai/gym#917] opened 2018-03-01 09:42 UTC
Hello, everybody,
 when running env of FetchPickAndPlace-vo, I met a problem that “Error: GLEW initialization error: Missing GL version”!
 How could I solve it?
Thanks

**Comment by JoyChopra1298** [comment] 2018-03-02 03:48
Refer this [issue.](https://github.com/openai/mujoco-py/pull/145) .

**Comment by teostoleru** [comment] 2019-02-06 19:00
@xhzcyc adding
LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libGLEW.so:/usr/lib/x86_64-linux-gnu/libGLEW.so.2.0:/usr/lib/x86_64-linux-gnu/libGLEW.so.2.0.0
to bashrc helped me solve the issue.

**Comment by christopherhesse** [comment] 2019-04-26 22:34
This sounds like a duplicate of this mujoco_py issue: https://github.com/openai/mujoco-py/pull/145

Please file a new issue on mujoco_py if it's not the same issue.  Thanks!

**Closed by christopherhesse** 2019-04-26 22:34 UTC
