### ISSUE TITLE
[Bug Report] pygame is required but is not listed in package setup requirements

### ISSUE THREAD

**Issue by piteren** [openai/gym#2781] opened 2022-04-27 18:12 UTC
**Describe the bug**
gym/envs/classic_control/cartpole.py imports pygame but it is not listed in package setup requirements

**Code example**
gym.make('CartPole-v1')

**System Info**
gym installed with pip
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
Python 3.7.13

- [x] I have checked that there is no similar [issue](https://github.com/openai/gym/issues) in the repo (**required**)

**Comment by balisujohn** [comment] 2022-04-27 20:03
What version of gym do you have installed?

**Comment by piteren** [comment] 2022-04-27 20:13
with:
pip install gym
I have installed:
gym                          0.23.1

**Comment by balisujohn** [comment] 2022-04-27 21:08
pygame is listed in [requirements.txt](https://github.com/openai/gym/blob/master/requirements.txt) in the version of gym you're using. I'm not super knowledgeable about pip packaging; is there a particular config file you're referring to when you say pygame is missing from the package setup requirements?

**Comment by piteren** [comment] 2022-04-27 21:16
Yes, it is listed in requirements.txt, but as far as I know it should be also listed in setup.py in install_requires [line 48] section for package proper installation.

**Comment by balisujohn** [comment] 2022-04-27 21:32
try

`pip install gym[box2d]`

or 

`pip install gym[all]`

**Comment by piteren** [comment] 2022-04-27 21:40
I have just installed pygame separately with
`pip install pygame`
and it works for me.

**Comment by pseudo-rnd-thoughts** [comment] 2022-04-27 23:20
@piteren Thanks for the comment, this is a fix we have made in the current master branch however it is not in the current release. 
We hope it will be released soon

**Closed** 2022-04-29 22:34 UTC

**Comment by bluenote10** [comment] 2022-04-30 13:23
Nonetheless this is a regression in a sense, because it makes the basic [tutorial](https://gym.openai.com/docs/) invalid.

Following the suggested steps of the tutorial is an error now:

```sh
$ virtualenv /tmp/tmp_venv -p /usr/bin/python3.8
$ pip install gym
$ python -c "import gym; gym.make('CartPole-v0')"
```

This used to work fine with gym version 0.21.0. In fact, it looks like in 0.21 it wasn't necessary to have pygame installed to use the cartpole env. It is a bit unfortunate that the env now requires such a "dirty" / heavy dependency as pygame :confused: I'd prefer to use the cartpole env without pygame like it was in 0.21.

**Comment by pseudo-rnd-thoughts** [comment] 2022-04-30 20:02
@bluenote10 Thanks for the comment, I understand your annoyance. 
The reason for the problem was that we changed to pygame as the rendering module however pygame was imported even if the user didn't want to render the environment. 
In the next release that we have hoping to release in the next week or so, we have made this an optional module that is only required for rendering.
