### ISSUE TITLE
[Question] Evaluate policy doesn't work

### ISSUE THREAD

**Issue by Shivam310** [openai/gym#3078] opened 2022-09-08 15:29 UTC
### Question

Whenever I my evaluate policy command, ie. this:
`mean_reward, std_reward = evaluate_policy(model, model.get_env(), n_eval_episodes=10, render=True)`
I get this error:
```
AttributeError                            Traceback (most recent call last)
Input In [9], in <cell line: 1>()
----> 1 mean_reward, std_reward = evaluate_policy(model, model.get_env(), n_eval_episodes=10, render=True)

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\stable_baselines3\common\evaluation.py:82, in evaluate_policy(model, env, n_eval_episodes, deterministic, render, callback, reward_threshold, return_episode_rewards, warn)
     80 current_rewards = np.zeros(n_envs)
     81 current_lengths = np.zeros(n_envs, dtype="int")
---> 82 observations = env.reset()
     83 states = None
     84 episode_starts = np.ones((env.num_envs,), dtype=bool)

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\stable_baselines3\common\vec_env\vec_transpose.py:110, in VecTransposeImage.reset(self)
    106 def reset(self) -> Union[np.ndarray, Dict]:
    107     """
    108     Reset all environments
    109     """
--> 110     return self.transpose_observations(self.venv.reset())

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\stable_baselines3\common\vec_env\vec_frame_stack.py:58, in VecFrameStack.reset(self)
     54 def reset(self) -> Union[np.ndarray, Dict[str, np.ndarray]]:
     55     """
     56     Reset all environments
     57     """
---> 58     observation = self.venv.reset()  # pytype:disable=annotation-type-mismatch
     60     observation = self.stackedobs.reset(observation)
     61     return observation

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\stable_baselines3\common\vec_env\dummy_vec_env.py:63, in DummyVecEnv.reset(self)
     61 def reset(self) -> VecEnvObs:
     62     for env_idx in range(self.num_envs):
---> 63         obs = self.envs[env_idx].reset()
     64         self._save_obs(env_idx, obs)
     65     return self._obs_from_buf()

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\gym\core.py:292, in Wrapper.reset(self, **kwargs)
    291 def reset(self, **kwargs):
--> 292     return self.env.reset(**kwargs)

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\gym\core.py:333, in RewardWrapper.reset(self, **kwargs)
    332 def reset(self, **kwargs):
--> 333     return self.env.reset(**kwargs)

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\gym\core.py:319, in ObservationWrapper.reset(self, **kwargs)
    318 def reset(self, **kwargs):
--> 319     observation = self.env.reset(**kwargs)
    320     return self.observation(observation)

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\stable_baselines3\common\atari_wrappers.py:59, in FireResetEnv.reset(self, **kwargs)
     58 def reset(self, **kwargs) -> np.ndarray:
---> 59     self.env.reset(**kwargs)
     60     obs, _, done, _ = self.env.step(1)
     61     if done:

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\stable_baselines3\common\atari_wrappers.py:106, in EpisodicLifeEnv.reset(self, **kwargs)
     97 """
     98 Calls the Gym environment reset, only when lives are exhausted.
     99 This way all states are still reachable even though lives are episodic,
   (...)
    103 :return: the first observation of the environment
    104 """
    105 if self.was_real_done:
--> 106     obs = self.env.reset(**kwargs)
    107 else:
    108     # no-op step to advance from terminal/lost life state
    109     obs, _, _, _ = self.env.step(0)

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\stable_baselines3\common\atari_wrappers.py:154, in MaxAndSkipEnv.reset(self, **kwargs)
    153 def reset(self, **kwargs) -> GymObs:
--> 154     return self.env.reset(**kwargs)

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\stable_baselines3\common\atari_wrappers.py:36, in NoopResetEnv.reset(self, **kwargs)
     34     noops = self.override_num_noops
     35 else:
---> 36     noops = self.unwrapped.np_random.randint(1, self.noop_max + 1)
     37 assert noops > 0
     38 obs = np.zeros(0)

AttributeError: 'numpy.random._generator.Generator' object has no attribute 'randint'
```
Please help thanks.

**Comment by pseudo-rnd-thoughts** [comment] 2022-09-08 16:07
Are you using the current gym version for stable baseline 3?

**Comment by araffin** [comment] 2022-09-08 21:19
you already opened an issue in SB3 and we already answered... https://github.com/DLR-RM/stable-baselines3/issues/977

Duplicate of https://github.com/DLR-RM/stable-baselines3/issues/875

**Comment by pseudo-rnd-thoughts** [comment] 2022-09-08 21:36
@Shivam310 Could you check if an issue has already been opened before opening new issues

**Comment by Shivam310** [comment] 2022-09-09 04:55
> @Shivam310 Could you check if an issue has already been opened before opening new issues

I am extremely sorry, I may have forgotten about it. I am fairly new to using github. I will make sure to check next time.

**Closed** 2022-09-09 05:22 UTC
